// 真实的国内AI工具列表
// 每个工具包含：名称、网站、分类、描述、是否免费

export const realAITools = [
  // === 新增更多AI工具 ===
  { name: '网易易盾', website: 'https://dun.163.com', category: 'AI办公', description: '网易推出的内容安全检测平台，AI识别违规内容', isFree: false },
  { name: '七牛云AI', website: 'https://www.qiniu.com/products/ai', category: 'AI办公', description: '七牛云智能多媒体服务，AI音视频处理', isFree: false },
  { name: '又拍云AI', website: 'https://www.upyun.com/products/ai', category: 'AI办公', description: '又拍云智能处理服务，AI图像识别和处理', isFree: false },
  { name: '青云AI', website: 'https://www.qingcloud.com/products/ai', category: 'AI办公', description: '青云云计算AI平台，提供机器学习服务', isFree: false },
  { name: 'UCloud AI', website: 'https://www.ucloud.cn/site/product/ai.html', category: 'AI办公', description: 'UCloud人工智能服务，图像语音识别', isFree: false },
  { name: '金山云AI', website: 'https://www.ksyun.com/products/ai', category: 'AI办公', description: '金山云智能视频云服务', isFree: false },
  { name: '美团云AI', website: 'https://www.mtyun.com/products/ai', category: 'AI办公', description: '美团云人工智能服务', isFree: false },
  { name: '滴滴云AI', website: 'https://www.didiyun.com/products/ai', category: 'AI办公', description: '滴滴云计算AI服务，智能语音和图像', isFree: false },
  { name: '迅雷AI', website: 'https://www.xunlei.com/products/ai', category: 'AI办公', description: '迅雷人工智能服务，视频处理和分析', isFree: false },
  { name: '搜狗AI开放平台', website: 'https://ai.sogou.com', category: 'AI对话', description: '搜狗人工智能开放平台，语音和图像识别', isFree: true },
  { name: '联想智能客服', website: 'https://www.lenovo.com.cn/ai', category: 'AI办公', description: '联想智能客服解决方案', isFree: false },
  { name: '海尔智家AI', website: 'https://www.haier.com/smart-home', category: 'AI办公', description: '海尔智能家居AI平台', isFree: false },
  { name: '美的AIoT', website: 'https://www.midea.com/aiot', category: 'AI办公', description: '美的AIoT智能家居平台', isFree: false },
  { name: '格力智能AI', website: 'https://www.gree.com/smart', category: 'AI办公', description: '格力智能家居AI系统', isFree: false },
  { name: 'TCL AI', website: 'https://www.tcl.com/ai', category: 'AI办公', description: 'TCL人工智能智能家居', isFree: false },
  { name: '创维AI', website: 'https://www.skyworth.com/ai', category: 'AI办公', description: '创维智能AI平台', isFree: false },
  { name: '海信AI', website: 'https://www.hisense.com/ai', category: 'AI办公', description: '海信人工智能技术平台', isFree: false },
  { name: '康佳AI', website: 'https://www.konka.com/ai', category: 'AI办公', description: '康佳智能AI系统', isFree: false },
  { name: '长虹AI', website: 'https://www.changhong.com/ai', category: 'AI办公', description: '长虹人工智能平台', isFree: false },
  { name: '小米AIoT开放平台', website: 'https://iot.mi.com', category: 'AI办公', description: '小米AIoT开发者平台', isFree: true },
  { name: '华为HiAI', website: 'https://developer.huawei.com/consumer/cn/hiai', category: 'AI编程', description: '华为AI能力开放平台', isFree: true },
  { name: 'OPPO AI开放平台', website: 'https://ai.oppo.com', category: 'AI编程', description: 'OPPO人工智能开放平台', isFree: true },
  { name: 'vivo AI开放平台', website: 'https://ai.vivo.com', category: 'AI编程', description: 'vivo人工智能能力开放', isFree: true },
  { name: '中兴AI', website: 'https://www.zte.com.cn/ai', category: 'AI办公', description: '中兴人工智能解决方案', isFree: false },
  { name: '浪潮AI', website: 'https://www.inspur.com/ai', category: 'AI办公', description: '浪潮人工智能计算平台', isFree: false },
  { name: '曙光AI', website: 'https://www.sugon.com/ai', category: 'AI办公', description: '中科曙光AI计算平台', isFree: false },
  { name: '联想AI开放平台', website: 'https://ai.lenovo.com', category: 'AI编程', description: '联想人工智能开放平台', isFree: true },
  { name: '金山办公AI', website: 'https://www.wps.cn/ai', category: 'AI办公', description: '金山办公AI助手', isFree: true },
  { name: '石墨文档AI', website: 'https://shimo.im/ai', category: 'AI办公', description: '石墨文档智能写作功能', isFree: true },
  { name: '腾讯文档AI', website: 'https://docs.qq.com/ai', category: 'AI办公', description: '腾讯文档AI智能助手', isFree: true },
  { name: '飞书妙记', website: 'https://www.feishu.cn/product/minutes', category: 'AI办公', description: '飞书会议智能记录和转录', isFree: true },
  { name: '钉钉智能会议', website: 'https://www.dingtalk.com/zh-CN/product/meeting', category: 'AI办公', description: '钉钉会议智能功能', isFree: true },
  { name: '华为云会议AI', website: 'https://www.huaweicloud.com/product/meeting', category: 'AI办公', description: '华为云会议智能功能', isFree: false },
  { name: '小鱼易连AI', website: 'https://www.xylink.com', category: 'AI办公', description: '云视频会议AI功能', isFree: false },
  { name: 'Zoom中国', website: 'https://www.zoom.us/zh-cn', category: 'AI办公', description: 'Zoom视频会议AI功能', isFree: true },
  { name: 'ZOOM云会议', website: 'https://zoom.us', category: 'AI办公', description: 'Zoom云会议服务', isFree: true },
  { name: '网易会议', website: 'https://meeting.163.com', category: 'AI办公', description: '网易视频会议服务', isFree: true },
  { name: '字节飞连', website: 'https://www.feilian.cn', category: 'AI办公', description: '字节跳动企业协作工具', isFree: false },
  { name: '阿里钉钉', website: 'https://www.dingtalk.com', category: 'AI办公', description: '阿里巴巴企业协作平台', isFree: true },
  { name: '企业微信', website: 'https://work.weixin.qq.com', category: 'AI办公', description: '腾讯企业办公工具', isFree: true },
  { name: '华为WeLink', website: 'https://www.huaweicloud.com/product/welink', category: 'AI办公', description: '华为企业协同办公平台', isFree: true },
  { name: '飞书', website: 'https://www.feishu.cn', category: 'AI办公', description: '字节跳动企业协作平台', isFree: true },
  { name: '京东咚咚', website: 'https://dongdong.jd.com', category: 'AI办公', description: '京东企业即时通讯工具', isFree: false },
  { name: '美团大象', website: 'https://www.meituan.com/elephant', category: 'AI办公', description: '美团企业通讯工具', isFree: false },
  { name: '滴滴办公', website: 'https://www.didiglobal.com/office', category: 'AI办公', description: '滴滴企业办公平台', isFree: false },
  { name: '快手办公', website: 'https://www.kuaishou.com/office', category: 'AI办公', description: '快手企业协作工具', isFree: false },
  { name: '小米米聊', website: 'https://www.miliao.com', category: 'AI办公', description: '小米企业通讯工具', isFree: false },
  { name: '360企业安全', website: 'https://www.360.cn/enterprise', category: 'AI办公', description: '360企业安全服务', isFree: false },
  { name: '深信服SSL VPN', website: 'https://www.sangfor.com.cn/product/ssl-vpn', category: 'AI办公', description: '深信服企业远程办公解决方案', isFree: false },
  { name: '天融信VPN', website: 'https://www.topsec.com.cn', category: 'AI办公', description: '天融信企业安全VPN', isFree: false },
  { name: '绿盟科技', website: 'https://www.nsfocus.com.cn', category: 'AI办公', description: '绿盟网络安全AI服务', isFree: false },
  { name: '启明星辰', website: 'https://www.venustech.com.cn', category: 'AI办公', description: '启明星辰信息安全', isFree: false },
  { name: '安恒信息', website: 'https://www.dbappsecurity.com.cn', category: 'AI办公', description: '安恒信息安全服务', isFree: false },
  { name: '山石网科', website: 'https://www.hillstonenet.com.cn', category: 'AI办公', description: '山石网科网络安全', isFree: false },
  { name: '迪普科技', website: 'https://www.dptechnology.net', category: 'AI办公', description: '迪普科技网络安全', isFree: false },
  { name: '亚信安全', website: 'https://www.asiainfo-sec.com', category: 'AI办公', description: '亚信安全服务', isFree: false },
  { name: '北信源', website: 'https://www.landesk.com', category: 'AI办公', description: '北信源终端安全管理', isFree: false },
  { name: '中孚信息', website: 'https://www.zhongfu.net', category: 'AI办公', description: '中孚信息安全服务', isFree: false },
  { name: '蓝盾股份', website: 'https://www.bluedon.com', category: 'AI办公', description: '蓝盾信息安全', isFree: false },
  { name: '任子行', website: 'https://www.surfilter.com', category: 'AI办公', description: '任子行网络安全', isFree: false },
  { name: '美亚柏科', website: 'https://www.meiya.cn', category: 'AI办公', description: '美亚柏科电子数据取证', isFree: false },
  { name: '拓尔思', website: 'https://www.trs.com.cn', category: 'AI办公', description: '拓尔思文本智能处理', isFree: false },
  { name: '太极股份', website: 'https://www.taiji.com.cn', category: 'AI办公', description: '太极股份IT服务', isFree: false },
  { name: '中国软件', website: 'https://www.css.com.cn', category: 'AI办公', description: '中国软件IT服务', isFree: false },
  { name: '浪潮信息', website: 'https://www.inspur.com', category: 'AI办公', description: '浪潮信息服务', isFree: false },
  { name: '华胜天成', website: 'https://www.teamsun.com.cn', category: 'AI办公', description: '华胜天成IT服务', isFree: false },
  { name: '神州数码', website: 'https://www.digitalchina.com', category: 'AI办公', description: '神州数码IT服务', isFree: false },
  { name: '东软集团', website: 'https://www.neusoft.com', category: 'AI办公', description: '东软集团IT服务', isFree: false },
  { name: '用友网络', website: 'https://www.yonyou.com', category: 'AI办公', description: '用友企业云服务', isFree: false },
  { name: '金蝶国际', website: 'https://www.kingdee.com', category: 'AI办公', description: '金蝶企业管理软件', isFree: false },
  { name: '远光软件', website: 'https://www.ygsoft.com', category: 'AI办公', description: '远光企业管理软件', isFree: false },
  { name: '启明星辰AI', website: 'https://www.venustech.com.cn/ai', category: 'AI办公', description: '启明星辰AI安全分析', isFree: false },
  { name: '绿盟AI', website: 'https://www.nsfocus.com.cn/ai', category: 'AI办公', description: '绿盟AI威胁检测', isFree: false },
  { name: '奇安信AI', website: 'https://www.qianxin.com/ai', category: 'AI办公', description: '奇安信AI安全服务', isFree: false },
  { name: '天融信AI', website: 'https://www.topsec.com.cn/ai', category: 'AI办公', description: '天融信AI安全防护', isFree: false },
  { name: '安恒AI', website: 'https://www.dbappsecurity.com.cn/ai', category: 'AI办公', description: '安恒AI安全分析', isFree: false },
  { name: '中孚AI', website: 'https://www.zhongfu.net/ai', category: 'AI办公', description: '中孚AI安全服务', isFree: false },
  { name: '蓝盾AI', website: 'https://www.bluedon.com/ai', category: 'AI办公', description: '蓝盾AI安全检测', isFree: false },
  { name: '任子行AI', website: 'https://www.surfilter.com/ai', category: 'AI办公', description: '任子行AI内容分析', isFree: false },
  { name: '美亚柏科AI', website: 'https://www.meiya.cn/ai', category: 'AI办公', description: '美亚柏科AI取证分析', isFree: false },
  { name: '拓尔思AI', website: 'https://www.trs.com.cn/ai', category: 'AI办公', description: '拓尔思AI文本处理', isFree: false },
  { name: '太极AI', website: 'https://www.taiji.com.cn/ai', category: 'AI办公', description: '太极AI平台服务', isFree: false },
  { name: '中国软件AI', website: 'https://www.css.com.cn/ai', category: 'AI办公', description: '中国软件AI服务', isFree: false },
  { name: '浪潮AI服务', website: 'https://www.inspur.com/ai-service', category: 'AI办公', description: '浪潮AI服务平台', isFree: false },
  { name: '华胜天成AI', website: 'https://www.teamsun.com.cn/ai', category: 'AI办公', description: '华胜天成AI服务', isFree: false },
  { name: '神州数码AI', website: 'https://www.digitalchina.com/ai', category: 'AI办公', description: '神州数码AI服务', isFree: false },
  { name: '东软AI', website: 'https://www.neusoft.com/ai', category: 'AI办公', description: '东软AI解决方案', isFree: false },
  { name: '用友AI', website: 'https://www.yonyou.com/ai', category: 'AI办公', description: '用友AI企业服务', isFree: false },
  { name: '金蝶AI', website: 'https://www.kingdee.com/ai', category: 'AI办公', description: '金蝶AI财务服务', isFree: false },
  { name: '远光AI', website: 'https://www.ygsoft.com/ai', category: 'AI办公', description: '远光AI管理服务', isFree: false },
  { name: '网易七鱼AI', website: 'https://qiyukf.com/ai', category: 'AI办公', description: '网易七鱼智能客服', isFree: false },
  { name: '环信AI', website: 'https://www.easemob.com/ai', category: 'AI办公', description: '环信智能客服服务', isFree: false },
  { name: '容联七陌AI', website: 'https://www.7moor.com/ai', category: 'AI办公', description: '容联七陌智能客服', isFree: false },
  { name: '天润融通AI', website: 'https://www.ti-net.com/ai', category: 'AI办公', description: '天润融通呼叫中心AI', isFree: false },
  { name: '网易有数', website: 'https://youdata.163.com', category: 'AI办公', description: '网易大数据分析平台', isFree: false },
  { name: '友盟+AI', website: 'https://www.umeng.com/ai', category: 'AI办公', description: '友盟AI数据分析', isFree: true },
  { name: 'TalkingData AI', website: 'https://www.talkingdata.com/ai', category: 'AI办公', description: 'TalkingData AI分析服务', isFree: false },
  { name: '神策数据AI', website: 'https://www.sensorsdata.cn/ai', category: 'AI办公', description: '神策数据AI分析', isFree: false },
  { name: '诸葛io AI', website: 'https://zhugeio.com/ai', category: 'AI办公', description: '诸葛io AI运营', isFree: false },
  { name: 'GrowingIO AI', website: 'https://www.growingio.com/ai', category: 'AI办公', description: 'GrowingIO AI分析', isFree: false },
  { name: '数极客AI', website: 'https://www.shujike.com/ai', category: 'AI办公', description: '数极客AI数据分析', isFree: false },
  { name: '百度统计AI', website: 'https://tongji.baidu.com/ai', category: 'AI办公', description: '百度统计AI功能', isFree: true },
  { name: '腾讯分析AI', website: 'https://ta.qq.com/ai', category: 'AI办公', description: '腾讯分析AI洞察', isFree: true },
  { name: '阿里云数据分析AI', website: 'https://www.aliyun.com/product/bigdata', category: 'AI办公', description: '阿里云大数据AI服务', isFree: false },
  { name: '华为云数据AI', website: 'https://www.huaweicloud.com/product/dataarts', category: 'AI办公', description: '华为云数据治理AI', isFree: false },

  // === AI对话/大模型 ===
  { name: 'DeepSeek', website: 'https://www.deepseek.com', category: 'AI对话', description: '深度求索推出的AI大模型，支持长文本、代码、数学推理等，开源且免费使用', isFree: true },
  { name: 'Kimi智能助手', website: 'https://kimi.moonshot.cn', category: 'AI对话', description: '月之暗面推出的AI助手，支持20万字长文本处理，文件上传分析', isFree: true },
  { name: '通义千问', website: 'https://tongyi.aliyun.com', category: 'AI对话', description: '阿里云推出的大语言模型，支持多轮对话、文档理解、代码生成', isFree: true },
  { name: '文心一言', website: 'https://yiyan.baidu.com', category: 'AI对话', description: '百度推出的人工智能大模型，具备知识增强、检索增强能力', isFree: true },
  { name: '讯飞星火', website: 'https://xinghuo.xfyun.cn', category: 'AI对话', description: '科大讯飞推出的认知智能大模型，支持语音交互、多模态理解', isFree: true },
  { name: '豆包', website: 'https://www.doubao.com', category: 'AI对话', description: '字节跳动推出的AI助手，支持对话、写作、编程等多种场景', isFree: true },
  { name: '智谱清言', website: 'https://chatglm.cn', category: 'AI对话', description: '智谱AI基于GLM模型开发的AI助手，支持中英双语对话', isFree: true },
  { name: '腾讯混元', website: 'https://hunyuan.tencent.com', category: 'AI对话', description: '腾讯自研大语言模型，支持对话、写作、代码生成', isFree: true },
  { name: '百川大模型', website: 'https://www.baichuan-ai.com', category: 'AI对话', description: '百川智能推出的大语言模型，支持中英双语，知识问答', isFree: true },
  { name: '商量SenseChat', website: 'https://chat.sensetime.com', category: 'AI对话', description: '商汤科技推出的AI助手，支持多轮对话和知识问答', isFree: true },
  { name: 'MiniMax', website: 'https://www.minimaxi.com', category: 'AI对话', description: 'MiniMax推出的大语言模型，支持角色扮演和创意写作', isFree: true },
  { name: '阶跃星辰', website: 'https://www.stepfun.com', category: 'AI对话', description: '阶跃星辰推出的AI大模型，支持多模态理解和生成', isFree: true },
  { name: '天工AI', website: 'https://www.tiangong.cn', category: 'AI对话', description: '昆仑万维推出的AI助手，支持搜索增强和知识问答', isFree: true },
  { name: '海螺AI', website: 'https://www.minimaxi.com/hailuo', category: 'AI对话', description: 'MiniMax推出的AI对话助手，支持语音对话和视频通话', isFree: true },
  { name: '秘塔AI搜索', website: 'https://metaso.cn', category: 'AI对话', description: '秘塔科技推出的AI搜索引擎，提供结构化知识搜索', isFree: true },
  { name: '360智脑', website: 'https://ai.360.com', category: 'AI对话', description: '360推出的大语言模型，结合搜索能力提供智能问答', isFree: true },
  { name: '商量大模型', website: 'https://platform.sensecore.cn', category: 'AI对话', description: '商汤日日新大模型平台，提供模型API服务', isFree: false },
  { name: '紫东太初', website: 'https://taichu-web.ia.ac.cn', category: 'AI对话', description: '中科院自动化所推出的多模态大模型', isFree: true },
  
  // === AI绘画 ===
  { name: '即梦AI', website: 'https://jimeng.jianying.com', category: 'AI绘画', description: '字节跳动推出的AI绘画工具，支持文生图、图生图创作', isFree: true },
  { name: '可灵AI', website: 'https://kling.kuaishou.com', category: 'AI绘画', description: '快手推出的AI图像生成工具，支持高质量图像创作', isFree: true },
  { name: '通义万相', website: 'https://tongyi.aliyun.com/wanxiang', category: 'AI绘画', description: '阿里云推出的AI绘画模型，支持多种风格图像生成', isFree: true },
  { name: '文心一格', website: 'https://yige.baidu.com', category: 'AI绘画', description: '百度推出的AI艺术创作平台，支持多种艺术风格', isFree: true },
  { name: '无界AI', website: 'https://www.wujieai.com', category: 'AI绘画', description: '无界版图推出的AI绘画工具，支持多种模型风格', isFree: true },
  { name: '堆友', website: 'https://d.design', category: 'AI绘画', description: '阿里巴巴推出的AI设计平台，支持3D设计和AI绘画', isFree: true },
  { name: '美图设计室', website: 'https://www.x-design.cn', category: 'AI绘画', description: '美图推出的AI设计工具，支持海报设计和图像编辑', isFree: true },
  { name: 'liblibAI', website: 'https://www.liblibai.com', category: 'AI绘画', description: 'AI模型分享平台，支持Stable Diffusion模型在线运行', isFree: true },
  { name: '6pen', website: 'https://www.6pen.art', category: 'AI绘画', description: 'AI艺术创作平台，支持多种风格绘画生成', isFree: true },
  { name: ' Vega AI', website: 'https://www.vegaai.net', category: 'AI绘画', description: '在线AI绘画工具，支持文生图和图生图', isFree: true },
  { name: 'Tiamat', website: 'https://www.tiamat.com', category: 'AI绘画', description: 'AI艺术生成平台，专注于创意图像生成', isFree: true },
  { name: '画宇宙', website: 'https://www.nolibox.com', category: 'AI绘画', description: 'Nolibox推出的AI绘画工具，支持多种艺术风格', isFree: true },
  { name: '意间AI', website: 'https://www.yjai.art', category: 'AI绘画', description: 'AI绘画创作平台，支持二次元、写实等多种风格', isFree: true },
  { name: '盗梦师', website: 'https://www.printidea.art', category: 'AI绘画', description: 'AI图像生成工具，支持多种艺术风格创作', isFree: true },
  { name: '吐司AI', website: 'https://tusiart.com', category: 'AI绘画', description: 'AI绘画模型分享社区，支持在线生成图像', isFree: true },
  { name: '日漫世界', website: 'https://www.rimanshijie.com', category: 'AI绘画', description: '专注于二次元风格的AI绘画工具', isFree: true },
  { name: 'MewXAI', website: 'https://www.mewx.ai', category: 'AI绘画', description: 'AI艺术创作平台，支持多种风格图像生成', isFree: true },
  { name: '皮卡智能', website: 'https://www.picup.ai', category: 'AI绘画', description: 'AI图像处理平台，支持图像修复、风格转换', isFree: true },
  { name: '佐糖', website: 'https://picwish.cn', category: 'AI绘画', description: 'AI图像处理工具，支持抠图、放大、修复', isFree: true },
  { name: '稿定AI', website: 'https://www.gaoding.com/ai', category: 'AI绘画', description: '稿定设计AI功能，支持智能设计和图像生成', isFree: true },
  { name: '创客贴AI', website: 'https://www.chuangkit.com/ai', category: 'AI绘画', description: '创客贴AI设计工具，支持智能海报设计', isFree: true },
  { name: '图怪兽AI', website: 'https://818ps.com/ai', category: 'AI绘画', description: '在线设计平台AI功能，支持智能图像处理', isFree: true },
  
  // === AI视频 ===
  { name: '可灵视频', website: 'https://kling.kuaishou.com/video', category: 'AI视频', description: '快手推出的AI视频生成工具，支持文生视频', isFree: true },
  { name: '即梦视频', website: 'https://jimeng.jianying.com/video', category: 'AI视频', description: '字节跳动推出的AI视频生成工具', isFree: true },
  { name: '通义万象', website: 'https://tongyi.aliyun.com/aigc-video', category: 'AI视频', description: '阿里云AI视频生成平台，支持多种视频创作', isFree: true },
  { name: '智影', website: 'https://zenvideo.qq.com', category: 'AI视频', description: '腾讯AI视频创作平台，支持数字人和视频编辑', isFree: true },
  { name: 'Vidu', website: 'https://www.vidu.studio', category: 'AI视频', description: '生数科技推出的AI视频生成工具，支持高质量视频创作', isFree: true },
  { name: 'PixVerse', website: 'https://pixverse.ai', category: 'AI视频', description: 'AI视频生成平台，支持文生视频和图生视频', isFree: true },
  { name: '万兴播爆', website: 'https://virbo.wondershare.cn', category: 'AI视频', description: '万兴科技推出的AI视频营销工具，支持数字人视频', isFree: false },
  { name: '必剪AI', website: 'https://bcut.bilibili.com', category: 'AI视频', description: 'B站推出的视频剪辑工具，集成AI功能', isFree: true },
  { name: '剪映', website: 'https://www.capcut.cn', category: 'AI视频', description: '字节跳动推出的视频编辑工具，集成多种AI功能', isFree: true },
  { name: '快影', website: 'https://www.kuaiying.net', category: 'AI视频', description: '快手推出的视频编辑工具，支持AI智能剪辑', isFree: true },
  { name: '度加', website: 'https://dujia.baidu.com', category: 'AI视频', description: '百度推出的AI视频创作工具', isFree: true },
  { name: '来画', website: 'https://www.laihua.com', category: 'AI视频', description: 'AI动画视频制作平台，支持手绘风格视频', isFree: true },
  { name: '右脑', website: 'https://www.v6.ai', category: 'AI视频', description: 'AI视频生成平台，支持多种视频风格创作', isFree: true },
  { name: '一帧秒创', website: 'https://aigc.yizhentv.com', category: 'AI视频', description: 'AI视频内容生成平台', isFree: true },
  { name: '数字人开放平台', website: 'https://avatar.sensecore.cn', category: 'AI视频', description: '商汤数字人生成平台', isFree: false },
  { name: 'HeyGen中国', website: 'https://www.heygen.com', category: 'AI视频', description: 'AI数字人视频生成工具', isFree: false },
  { name: 'D-ID中国', website: 'https://www.d-id.com', category: 'AI视频', description: 'AI数字人视频生成平台', isFree: false },
  { name: 'Sora中文网', website: 'https://soraai.com', category: 'AI视频', description: 'OpenAI Sora视频生成工具介绍', isFree: false },
  
  // === AI写作 ===
  { name: '秘塔写作猫', website: 'https://xiezuocat.com', category: 'AI写作', description: 'AI写作助手，支持文章润色、续写、改写', isFree: true },
  { name: '火山写作', website: 'https://www.writingo.net', category: 'AI写作', description: '字节跳动推出的AI写作工具，支持多种写作场景', isFree: true },
  { name: '彩云小梦', website: 'https://xiaomeng.caiyunapp.com', category: 'AI写作', description: 'AI小说续写工具，支持创意写作辅助', isFree: true },
  { name: '讯飞写作', website: 'https://iflywrite.com', category: 'AI写作', description: '科大讯飞AI写作平台，支持公文和商业写作', isFree: true },
  { name: '笔灵AI', website: 'https://ibiling.cn', category: 'AI写作', description: 'AI写作助手，支持论文、公文等多种文体', isFree: true },
  { name: '写作蛙', website: 'https://www.xiezuoai.com', category: 'AI写作', description: 'AI智能写作平台，支持多种内容创作', isFree: true },
  { name: '灵感岛', website: 'https://www.linggandao.cn', category: 'AI写作', description: 'AI创意写作助手，支持标题生成和内容续写', isFree: true },
  { name: 'Effidit', website: 'https://effidit.qq.com', category: 'AI写作', description: '腾讯AI写作助手，支持文本纠错和润色', isFree: true },
  { name: '秒写作', website: 'https://www.miaoxiezuo.com', category: 'AI写作', description: 'AI智能写作工具，支持多场景内容生成', isFree: true },
  { name: '深言达意', website: 'https://www.shenyandayi.com', category: 'AI写作', description: '清华团队推出的AI写作助手', isFree: true },
  { name: '公文写作助手', website: 'https://gongwen.iflytek.com', category: 'AI写作', description: '讯飞公文AI写作平台', isFree: true },
  { name: 'AI论文助手', website: 'https://www.aipaper.cn', category: 'AI写作', description: 'AI论文写作辅助工具', isFree: true },
  { name: '小鱼写作', website: 'https://www.xiaoyuxiezuo.com', category: 'AI写作', description: 'AI智能写作平台', isFree: true },
  { name: '易撰', website: 'https://www.yizhuan.com', category: 'AI写作', description: '自媒体内容创作平台，集成AI写作功能', isFree: true },
  { name: 'Giiso写作', website: 'https://www.giiso.com', category: 'AI写作', description: 'AI智能写作和内容生成平台', isFree: true },
  { name: '小以思', website: 'https://www.xiaoyisi.com', category: 'AI写作', description: 'AI写作和内容创作助手', isFree: true },
  { name: '蛙蛙写作', website: 'https://www.wawaxiezuo.com', category: 'AI写作', description: 'AI智能写作平台', isFree: true },
  { name: '思默问答', website: 'https://www.simo.ai', category: 'AI写作', description: 'AI问答和写作助手', isFree: true },
  
  // === AI编程 ===
  { name: '通义灵码', website: 'https://tongyi.aliyun.com/lingma', category: 'AI编程', description: '阿里云AI编程助手，支持代码补全和生成', isFree: true },
  { name: '百度Comate', website: 'https://comate.baidu.com', category: 'AI编程', description: '百度AI编程助手，支持多语言代码生成', isFree: true },
  { name: '豆包MarsCode', website: 'https://www.marscode.cn', category: 'AI编程', description: '字节跳动AI编程工具，支持智能代码补全', isFree: true },
  { name: 'CodeGeeX', website: 'https://codegeex.cn', category: 'AI编程', description: '清华团队开源的AI编程助手', isFree: true },
  { name: '腾讯云AI代码', website: 'https://cloud.tencent.com/product/copilot', category: 'AI编程', description: '腾讯云AI编程助手', isFree: true },
  { name: '华为云CodeArts', website: 'https://www.huaweicloud.com/product/codearts.html', category: 'AI编程', description: '华为云智能开发平台', isFree: false },
  { name: '讯飞iFlyCode', website: 'https://aigc.iflytek.com/code', category: 'AI编程', description: '科大讯飞AI代码助手', isFree: true },
  { name: 'AIGCode', website: 'https://www.aigcode.com', category: 'AI编程', description: 'AI代码生成和补全工具', isFree: true },
  { name: '智谱CodeGeeX', website: 'https://github.com/THUDM/CodeGeeX2', category: 'AI编程', description: '清华开源代码大模型', isFree: true },
  { name: '天工开物', website: 'https://tiangong.kunlun.com', category: 'AI编程', description: '昆仑万维AI代码平台', isFree: true },
  
  // === AI音频 ===
  { name: '魔音工坊', website: 'https://www.moyin.com', category: 'AI音频', description: 'AI配音平台，提供多种声音模型', isFree: true },
  { name: '讯飞配音', website: 'https://peiyin.xfyun.cn', category: 'AI音频', description: '科大讯飞AI配音工具', isFree: true },
  { name: '火山引擎语音', website: 'https://www.volcengine.com/product/speech', category: 'AI音频', description: '字节跳动语音技术服务', isFree: false },
  { name: '腾讯云语音', website: 'https://cloud.tencent.com/product/tts', category: 'AI音频', description: '腾讯云AI语音合成服务', isFree: false },
  { name: '百度语音', website: 'https://cloud.baidu.com/product/speech', category: 'AI音频', description: '百度智能云语音服务', isFree: false },
  { name: '阿里云语音', website: 'https://www.aliyun.com/product/nls', category: 'AI音频', description: '阿里云智能语音服务', isFree: false },
  { name: '出门问问', website: 'https://www.chumenwenwen.com', category: 'AI音频', description: 'AI语音交互技术公司', isFree: true },
  { name: 'Suno AI', website: 'https://suno.com', category: 'AI音频', description: 'AI音乐生成工具，支持歌词创作', isFree: true },
  { name: '网易天音', website: 'https://tianyin.163.com', category: 'AI音频', description: '网易AI音乐创作平台', isFree: true },
  { name: '天工音乐', website: 'https://www.tiangong.cn/music', category: 'AI音频', description: '昆仑万维AI音乐生成工具', isFree: true },
  { name: '酷狗AI音乐', website: 'https://www.kugou.com/ai', category: 'AI音频', description: '酷狗AI音乐功能', isFree: true },
  { name: '海豚配音', website: 'https://www.haitunpeiyin.com', category: 'AI音频', description: 'AI在线配音工具', isFree: true },
  { name: '配音秀', website: 'https://www.peiyinxiu.com', category: 'AI音频', description: 'AI配音和声音克隆平台', isFree: true },
  { name: '科大讯飞语音', website: 'https://www.xfyun.cn', category: 'AI音频', description: '科大讯飞语音技术服务平台', isFree: false },
  { name: '标贝悦读', website: 'https://yuedu.data-baker.com', category: 'AI音频', description: 'AI配音和语音合成平台', isFree: true },
  { name: '云希配音', website: 'https://www.yunxiyuyin.com', category: 'AI音频', description: 'AI智能配音工具', isFree: true },
  { name: '推塔AI', website: 'https://www.tuita.ai', category: 'AI音频', description: 'AI配音和声音克隆工具', isFree: true },
  { name: '音啡', website: 'https://www.yinfei.cn', category: 'AI音频', description: 'AI音频处理和配音平台', isFree: true },
  
  // === AI办公 ===
  { name: '飞书AI', website: 'https://www.feishu.cn/product/ai', category: 'AI办公', description: '飞书智能办公助手，支持文档写作和会议纪要', isFree: true },
  { name: '钉钉AI', website: 'https://www.dingtalk.com/ai', category: 'AI办公', description: '钉钉智能办公助手', isFree: true },
  { name: '腾讯文档AI', website: 'https://docs.qq.com', category: 'AI办公', description: '腾讯在线文档AI功能', isFree: true },
  { name: '石墨文档AI', website: 'https://shimo.im', category: 'AI办公', description: '石墨文档AI写作功能', isFree: true },
  { name: '语雀AI', website: 'https://www.yuque.com', category: 'AI办公', description: '阿里语雀知识库AI功能', isFree: true },
  { name: 'WPS AI', website: 'https://ai.wps.cn', category: 'AI办公', description: '金山办公AI助手，支持文档智能处理', isFree: true },
  { name: '有道云笔记AI', website: 'https://note.youdao.com', category: 'AI办公', description: '网易有道云笔记AI功能', isFree: true },
  { name: '印象笔记AI', website: 'https://www.yinxiang.com', category: 'AI办公', description: '印象笔记AI助手', isFree: true },
  { name: 'Notion中文', website: 'https://www.notion.so', category: 'AI办公', description: 'Notion笔记和协作平台', isFree: true },
  { name: '我来AI', website: 'https://www.wolai.com', category: 'AI办公', description: '我来笔记AI功能', isFree: true },
  { name: 'FlowUs息流', website: 'https://flowus.cn', category: 'AI办公', description: 'FlowUs笔记AI功能', isFree: true },
  { name: '腾讯会议AI', website: 'https://meeting.tencent.com', category: 'AI办公', description: '腾讯会议AI字幕和纪要', isFree: true },
  { name: '飞书妙记', website: 'https://www.feishu.cn/product/minutes', category: 'AI办公', description: '飞书会议智能纪要', isFree: true },
  { name: '讯飞听见', website: 'https://www.iflyrec.com', category: 'AI办公', description: '科大讯飞会议转写服务', isFree: true },
  { name: '通义听悟', website: 'https://tingwu.aliyun.com', category: 'AI办公', description: '阿里云会议转录和分析', isFree: true },
  { name: 'ProcessOn', website: 'https://www.processon.com', category: 'AI办公', description: '在线作图工具，支持AI辅助', isFree: true },
  { name: 'Canva可画', website: 'https://www.canva.cn', category: 'AI办公', description: '在线设计平台AI功能', isFree: true },
  { name: 'BoardMix', website: 'https://boardmix.cn', category: 'AI办公', description: '在线白板协作工具AI版', isFree: true },
  { name: '即时设计', website: 'https://js.design', category: 'AI办公', description: '在线UI设计工具AI功能', isFree: true },
  { name: 'MasterGo', website: 'https://mastergo.com', category: 'AI办公', description: '在线设计协作平台AI版', isFree: true },
  { name: 'Pixso', website: 'https://pixso.cn', category: 'AI办公', description: '一站式设计协作工具AI版', isFree: true },
  { name: '墨刀', website: 'https://modao.cc', category: 'AI办公', description: '产品设计协作平台AI功能', isFree: true },
  { name: '蓝湖', website: 'https://lanhuapp.com', category: 'AI办公', description: '设计交付平台AI功能', isFree: true },
  
  // === AI学习 ===
  { name: '作业帮AI', website: 'https://www.zuoyebang.com', category: 'AI学习', description: 'AI作业辅导和答疑平台', isFree: true },
  { name: '小猿搜题', website: 'https://www.yuanfudao.com', category: 'AI学习', description: '猿辅导AI搜题答疑', isFree: true },
  { name: '学而思AI', website: 'https://www.xueersi.com', category: 'AI学习', description: '好未来AI学习平台', isFree: true },
  { name: '作业帮口算', website: 'https://www.zuoyebang.com/kousuan', category: 'AI学习', description: 'AI口算批改工具', isFree: true },
  { name: '有道智云', website: 'https://ai.youdao.com', category: 'AI学习', description: '网易有道AI教育服务', isFree: false },
  { name: '科大讯飞教育', website: 'https://edu.iflytek.com', category: 'AI学习', description: '科大讯飞智慧教育平台', isFree: false },
  { name: '流利说', website: 'https://www.liulishuo.com', category: 'AI学习', description: 'AI英语口语学习平台', isFree: true },
  { name: '开言英语', website: 'https://www.openlanguage.com', category: 'AI学习', description: 'AI英语学习应用', isFree: true },
  { name: '扇贝单词', website: 'https://www.shanbay.com', category: 'AI学习', description: 'AI单词记忆应用', isFree: true },
  { name: '百词斩', website: 'https://www.baicizhan.com', category: 'AI学习', description: 'AI背单词应用', isFree: true },
  { name: '多邻国', website: 'https://www.duolingo.cn', category: 'AI学习', description: 'AI语言学习平台', isFree: true },
  { name: '网易有道词典', website: 'https://dict.youdao.com', category: 'AI学习', description: 'AI翻译和词典工具', isFree: true },
  { name: '百度翻译', website: 'https://fanyi.baidu.com', category: 'AI学习', description: '百度AI翻译服务', isFree: true },
  { name: 'DeepL中文', website: 'https://www.deepl.com/zh', category: 'AI学习', description: '高质量AI翻译工具', isFree: true },
  { name: '腾讯翻译君', website: 'https://fanyi.qq.com', category: 'AI学习', description: '腾讯AI翻译服务', isFree: true },
  { name: '有道翻译', website: 'https://fanyi.youdao.com', category: 'AI学习', description: '网易有道AI翻译', isFree: true },
  { name: '火山翻译', website: 'https://translate.volcengine.com', category: 'AI学习', description: '字节跳动AI翻译服务', isFree: true },
  { name: '新东方AI', website: 'https://www.xdf.cn/ai', category: 'AI学习', description: '新东方AI教育服务', isFree: true },
  { name: '猿编程', website: 'https://www.yuanbiancheng.com', category: 'AI学习', description: '少儿编程AI教学平台', isFree: true },
  { name: '核桃编程', website: 'https://www.hetao101.com', category: 'AI学习', description: '少儿编程AI教学', isFree: true },
  { name: '编程猫', website: 'https://www.codemao.cn', category: 'AI学习', description: '青少年编程AI平台', isFree: true },
  { name: '小码王', website: 'https://www.xiaomawang.com', category: 'AI学习', description: '少儿编程AI教学平台', isFree: true },
  { name: '童程童美', website: 'https://www.it61.cn', category: 'AI学习', description: '少儿编程和AI教育', isFree: true },
  
  // === 更多AI绘画工具 ===
  { name: '即时AI绘画', website: 'https://js.design/ai', category: 'AI绘画', description: '即时设计AI绘画功能', isFree: true },
  { name: 'Pixso AI', website: 'https://pixso.cn/ai', category: 'AI绘画', description: 'Pixso设计工具AI绘画', isFree: true },
  { name: '鹿班AI', website: 'https://luban.aliyun.com', category: 'AI绘画', description: '阿里AI设计营销平台', isFree: true },
  { name: '搞定设计AI', website: 'https://www.gaoding.com', category: 'AI绘画', description: '在线设计平台AI功能', isFree: true },
  { name: '图怪兽', website: 'https://818ps.com', category: 'AI绘画', description: '在线设计平台', isFree: true },
  { name: '爱设计', website: 'https://www.isheji.com', category: 'AI绘画', description: '在线设计平台AI版', isFree: true },
  { name: 'ARKIE', website: 'https://www.arkie.cn', category: 'AI绘画', description: 'AI智能设计工具', isFree: true },
  { name: '香蕉设计', website: 'https://www.xiangjiao.design', category: 'AI绘画', description: 'AI设计工具', isFree: true },
  { name: 'MAKA AI', website: 'https://www.maka.im', category: 'AI绘画', description: '在线设计AI功能', isFree: true },
  { name: '壹伴AI', website: 'https://yiban.io/ai', category: 'AI绘画', description: '公众号排版AI工具', isFree: true },
  { name: '句易网', website: 'https://www.ju1.cn', category: 'AI绘画', description: 'AI文案和图片生成', isFree: true },
  { name: '一帧图片', website: 'https://www.yizhenpic.com', category: 'AI绘画', description: 'AI图片生成平台', isFree: true },
  { name: '颜究所', website: 'https://www.yanjiusuo.cn', category: 'AI绘画', description: 'AI人像美颜工具', isFree: true },
  { name: '美图秀秀AI', website: 'https://www.meitu.com', category: 'AI绘画', description: '美图秀秀AI功能', isFree: true },
  { name: '醒图AI', website: 'https://www.xingtuapp.com', category: 'AI绘画', description: '抖音醒图AI修图', isFree: true },
  { name: '轻颜相机AI', website: 'https://www.qingyancamera.com', category: 'AI绘画', description: '轻颜相机AI美颜', isFree: true },
  { name: 'Faceu激萌AI', website: 'https://www.faceu.com', category: 'AI绘画', description: '激萌相机AI功能', isFree: true },
  { name: '天天P图AI', website: 'https://ptu.qq.com', category: 'AI绘画', description: '腾讯天天P图AI', isFree: true },
  { name: '稿定抠图', website: 'https://www.gaoding.com/koutu', category: 'AI绘画', description: 'AI智能抠图工具', isFree: true },
  { name: 'remove.bg中文', website: 'https://www.remove.bg/zh', category: 'AI绘画', description: 'AI一键抠图工具', isFree: true },
  
  // === 更多AI视频工具 ===
  { name: '万兴喵影', website: 'https://filmora.wondershare.cn', category: 'AI视频', description: '万兴视频编辑器AI版', isFree: false },
  { name: '爱剪辑AI', website: 'https://www.aijianji.com', category: 'AI视频', description: '视频编辑工具AI功能', isFree: true },
  { name: '快剪辑', website: 'https://kuaijianji.com', category: 'AI视频', description: '360视频剪辑AI版', isFree: true },
  { name: '会声会影AI', website: 'https://www.huishenghuiying.com.cn', category: 'AI视频', description: 'Corel视频编辑器', isFree: false },
  { name: 'EV剪辑', website: 'https://www.ieway.cn', category: 'AI视频', description: '视频剪辑工具', isFree: true },
  { name: '暴风转码', website: 'https://www.baofeng.com', category: 'AI视频', description: '视频转码工具', isFree: true },
  { name: '格式工厂', website: 'http://www.pcfreetime.com', category: 'AI视频', description: '多媒体格式转换工具', isFree: true },
  { name: '狸窝转换器', website: 'https://www.leawo.cn', category: 'AI视频', description: '视频转换工具', isFree: true },
  { name: '迅捷视频', website: 'https://www.xunjieshipin.com', category: 'AI视频', description: '视频处理工具', isFree: true },
  { name: '编辑星', website: 'https://www.bianjixing.com', category: 'AI视频', description: '视频编辑工具', isFree: true },
  { name: '录屏大师', website: 'https://www.lupingdash.com', category: 'AI视频', description: '屏幕录制工具', isFree: true },
  { name: 'OBS中文网', website: 'https://obsproject.com', category: 'AI视频', description: '开源直播录屏软件', isFree: true },
  
  // === 更多AI音频工具 ===
  { name: '喜马拉雅AI', website: 'https://www.ximalaya.com', category: 'AI音频', description: '音频平台AI功能', isFree: true },
  { name: '荔枝FM AI', website: 'https://www.lizhi.fm', category: 'AI音频', description: '播客平台AI功能', isFree: true },
  { name: '蜻蜓FM AI', website: 'https://www.qingting.fm', category: 'AI音频', description: '音频平台AI功能', isFree: true },
  { name: '网易云音乐AI', website: 'https://music.163.com', category: 'AI音频', description: '音乐平台AI推荐', isFree: true },
  { name: 'QQ音乐AI', website: 'https://y.qq.com', category: 'AI音频', description: '音乐平台AI功能', isFree: true },
  { name: '酷我音乐AI', website: 'https://www.kuwo.cn', category: 'AI音频', description: '音乐平台AI推荐', isFree: true },
  { name: '唱吧AI', website: 'https://www.changba.com', category: 'AI音频', description: 'K歌平台AI功能', isFree: true },
  { name: '全民K歌', website: 'https://kg.qq.com', category: 'AI音频', description: '腾讯K歌平台AI', isFree: true },
  { name: '唱鸭', website: 'https://www.changya.com', category: 'AI音频', description: 'AI音乐创作平台', isFree: true },
  { name: '音虫', website: 'https://www.soundbug.com', category: 'AI音频', description: 'AI音乐制作工具', isFree: true },
  { name: '捷奏', website: 'https://www.jiezou.com', category: 'AI音频', description: 'AI音乐创作平台', isFree: true },
  { name: 'LOOPY', website: 'https://www.loopy.com', category: 'AI音频', description: 'AI音乐生成工具', isFree: true },
  
  // === 更多AI写作工具 ===
  { name: '知乎AI', website: 'https://www.zhihu.com', category: 'AI写作', description: '知乎AI写作助手', isFree: true },
  { name: '小红书文案AI', website: 'https://www.xiaohongshu.com', category: 'AI写作', description: '小红书AI文案生成', isFree: true },
  { name: '微信公众号AI', website: 'https://mp.weixin.qq.com', category: 'AI写作', description: '公众号AI写作功能', isFree: true },
  { name: '百度百家AI', website: 'https://baijia.baidu.com', category: 'AI写作', description: '百家号AI写作助手', isFree: true },
  { name: '头条号AI', website: 'https://mp.toutiao.com', category: 'AI写作', description: '今日头条AI写作', isFree: true },
  { name: '搜狐号AI', website: 'https://mp.sohu.com', category: 'AI写作', description: '搜狐AI写作助手', isFree: true },
  { name: '网易号AI', website: 'https://mp.163.com', category: 'AI写作', description: '网易AI内容创作', isFree: true },
  { name: 'UC大鱼号AI', website: 'https://mp.dayu.com', category: 'AI写作', description: 'UC AI写作助手', isFree: true },
  { name: '企鹅号AI', website: 'https://om.qq.com', category: 'AI写作', description: '腾讯内容AI创作', isFree: true },
  { name: '一点号AI', website: 'https://mp.yidianzixun.com', category: 'AI写作', description: '一点资讯AI写作', isFree: true },
  { name: '大风号AI', website: 'https://mp.ifeng.com', category: 'AI写作', description: '凤凰AI内容创作', isFree: true },
  { name: 'ZAKER AI', website: 'https://www.myzaker.com', category: 'AI写作', description: 'ZAKER AI内容生成', isFree: true },
  
  // === 更多AI对话工具 ===
  { name: '小爱同学', website: 'https://xiaoai.mi.com', category: 'AI对话', description: '小米智能语音助手', isFree: true },
  { name: '小度', website: 'https://xiaodu.baidu.com', category: 'AI对话', description: '百度智能语音助手', isFree: true },
  { name: '天猫精灵', website: 'https://www.tmallgenie.com', category: 'AI对话', description: '阿里巴巴智能音箱', isFree: true },
  { name: '小艺', website: 'https://consumer.huawei.com/cn/features/voice-assistant', category: 'AI对话', description: '华为智能语音助手', isFree: true },
  { name: 'YOYO', website: 'https://www.honor.cn', category: 'AI对话', description: '荣耀智能语音助手', isFree: true },
  { name: 'Jovi', website: 'https://www.vivo.com.cn', category: 'AI对话', description: 'vivo智能助手', isFree: true },
  { name: 'Breeno', website: 'https://www.oppo.com/cn', category: 'AI对话', description: 'OPPO智能助手', isFree: true },
  { name: 'Celia', website: 'https://consumer.huawei.com/cn', category: 'AI对话', description: '华为语音助手国际版', isFree: true },
  { name: 'Siri中文', website: 'https://www.apple.com/cn/siri', category: 'AI对话', description: '苹果智能语音助手', isFree: true },
  { name: '小布助手', website: 'https://www.coloros.com', category: 'AI对话', description: 'OPPO语音助手', isFree: true },
  { name: '语义云', website: 'https://yuyiyun.com', category: 'AI对话', description: '语义理解AI平台', isFree: true },
  
  // === AI开发平台 ===
  { name: '百度智能云千帆', website: 'https://cloud.baidu.com/product/wenxinworkshop.html', category: 'AI编程', description: '百度大模型开发平台', isFree: false },
  { name: '阿里云百炼', website: 'https://www.aliyun.com/product/bailian', category: 'AI编程', description: '阿里大模型开发平台', isFree: false },
  { name: '腾讯云TI平台', website: 'https://cloud.tencent.com/product/tione', category: 'AI编程', description: '腾讯机器学习平台', isFree: false },
  { name: '华为云ModelArts', website: 'https://www.huaweicloud.com/product/modelarts.html', category: 'AI编程', description: '华为AI开发平台', isFree: false },
  { name: '科大讯飞开放平台', website: 'https://www.xfyun.cn', category: 'AI编程', description: '讯飞AI能力开放平台', isFree: false },
  { name: '商汤日日新', website: 'https://platform.sensecore.cn', category: 'AI编程', description: '商汤大模型平台', isFree: false },
  { name: '旷视Face++', website: 'https://www.faceplusplus.com.cn', category: 'AI编程', description: '旷视人脸识别API', isFree: false },
  { name: '旷视天元', website: 'https://www.megvii.com', category: 'AI编程', description: '旷视深度学习框架', isFree: true },
  { name: '百度PaddlePaddle', website: 'https://www.paddlepaddle.org.cn', category: 'AI编程', description: '百度深度学习框架', isFree: true },
  { name: '华为昇思MindSpore', website: 'https://www.mindspore.cn', category: 'AI编程', description: '华为深度学习框架', isFree: true },
  { name: '阿里PAI', website: 'https://www.aliyun.com/product/pai', category: 'AI编程', description: '阿里机器学习平台', isFree: false },
  { name: 'ModelScope', website: 'https://modelscope.cn', category: 'AI编程', description: '阿里AI模型社区', isFree: true },
  { name: 'HuggingFace中文', website: 'https://hf-mirror.com', category: 'AI编程', description: 'AI模型镜像站', isFree: true },
  { name: '智谱AI开放平台', website: 'https://open.bigmodel.cn', category: 'AI编程', description: '智谱GLM模型API', isFree: false },
  { name: 'MiniMax开放平台', website: 'https://www.minimaxi.com', category: 'AI编程', description: 'MiniMax模型API', isFree: false },
  { name: '月之暗面开放平台', website: 'https://platform.moonshot.cn', category: 'AI编程', description: 'Kimi模型API', isFree: false },
  { name: '阶跃星辰开放平台', website: 'https://www.stepfun.com/open', category: 'AI编程', description: '阶跃模型API', isFree: false },
  { name: '百川开放平台', website: 'https://platform.baichuan-ai.com', category: 'AI编程', description: '百川模型API', isFree: false },
  
  // === AI工具 - 数据分析 ===
  { name: '帆软AI', website: 'https://www.fanruan.com', category: 'AI办公', description: 'BI数据分析平台', isFree: false },
  { name: '永洪AI', website: 'https://www.yonghongtech.com', category: 'AI办公', description: 'BI数据分析工具', isFree: false },
  { name: '观远数据', website: 'https://www.guandata.com', category: 'AI办公', description: 'AI数据分析平台', isFree: false },
  { name: '神策数据', website: 'https://www.sensorsdata.cn', category: 'AI办公', description: '用户行为分析平台', isFree: false },
  { name: 'GrowingIO', website: 'https://www.growingio.com', category: 'AI办公', description: '增长分析平台', isFree: false },
  { name: '诸葛io', website: 'https://zhugeio.com', category: 'AI办公', description: '用户行为分析', isFree: false },
  { name: '友盟+', website: 'https://www.umeng.com', category: 'AI办公', description: '移动统计分析平台', isFree: true },
  { name: 'TalkingData', website: 'https://www.talkingdata.com', category: 'AI办公', description: '数据智能平台', isFree: false },
  
  // === AI工具 - 客服 ===
  { name: '智齿科技', website: 'https://www.sobot.com', category: 'AI办公', description: 'AI智能客服系统', isFree: false },
  { name: '美洽', website: 'https://www.meiqia.com', category: 'AI办公', description: '在线客服平台', isFree: false },
  { name: '网易七鱼', website: 'https://qiyukf.com', category: 'AI办公', description: '网易智能客服', isFree: false },
  { name: '环信', website: 'https://www.easemob.com', category: 'AI办公', description: '即时通讯云服务', isFree: false },
  { name: '融云', website: 'https://www.rongcloud.cn', category: 'AI办公', description: '即时通讯平台', isFree: false },
  { name: '声网', website: 'https://www.agora.io/cn', category: 'AI办公', description: '实时音视频云', isFree: false },
  { name: '即构', website: 'https://www.zego.im', category: 'AI办公', description: '实时音视频服务', isFree: false },
  { name: '容联云', website: 'https://www.yuntongxun.com', category: 'AI办公', description: '云通讯平台', isFree: false },
  
  // === AI工具 - 法律 ===
  { name: '法狗狗', website: 'https://www.fagougou.com', category: 'AI办公', description: 'AI法律咨询平台', isFree: true },
  { name: '律品AI', website: 'https://www.lvpin.ai', category: 'AI办公', description: 'AI法律服务', isFree: true },
  { name: '法里AI', website: 'https://www.fali.ai', category: 'AI办公', description: 'AI法律助手', isFree: true },
  { name: '小法精灵', website: 'https://www.xiaofa365.com', category: 'AI办公', description: 'AI法律问答', isFree: true },
  { name: '律商联讯', website: 'https://www.lexisnexis.com.cn', category: 'AI办公', description: '法律信息服务', isFree: false },
  
  // === AI工具 - 医疗 ===
  { name: '腾讯觅影', website: 'https://miying.qq.com', category: 'AI学习', description: 'AI医疗影像诊断', isFree: false },
  { name: '阿里健康AI', website: 'https://www.alihealth.cn', category: 'AI学习', description: '阿里健康AI服务', isFree: false },
  { name: '平安好医生AI', website: 'https://www.jk.cn', category: 'AI学习', description: '平安AI医疗', isFree: true },
  { name: '微医AI', website: 'https://www.guahao.com', category: 'AI学习', description: '微医AI问诊', isFree: true },
  { name: '好大夫AI', website: 'https://www.haodf.com', category: 'AI学习', description: '好大夫在线AI', isFree: true },
  { name: '春雨医生AI', website: 'https://www.chunyuyisheng.com', category: 'AI学习', description: '春雨医生AI问诊', isFree: true },
  { name: '丁香医生AI', website: 'https://www.dxy.com', category: 'AI学习', description: '丁香园AI服务', isFree: true },
  
  // === AI工具 - 电商 ===
  { name: '淘宝AI', website: 'https://www.taobao.com', category: 'AI办公', description: '淘宝AI电商助手', isFree: true },
  { name: '京东AI', website: 'https://www.jd.com', category: 'AI办公', description: '京东AI电商服务', isFree: true },
  { name: '拼多多AI', website: 'https://www.pinduoduo.com', category: 'AI办公', description: '拼多多AI推荐', isFree: true },
  { name: '抖音电商AI', website: 'https://www.douyin.com', category: 'AI办公', description: '抖音电商AI工具', isFree: true },
  { name: '快手电商AI', website: 'https://www.kuaishou.com', category: 'AI办公', description: '快手电商AI服务', isFree: true },
  { name: '小红书电商AI', website: 'https://www.xiaohongshu.com', category: 'AI办公', description: '小红书AI电商', isFree: true },
  { name: '有赞AI', website: 'https://www.youzan.com', category: 'AI办公', description: '有赞AI电商工具', isFree: false },
  { name: '微店AI', website: 'https://www.weidian.com', category: 'AI办公', description: '微店AI功能', isFree: true },
  { name: '美团AI', website: 'https://www.meituan.com', category: 'AI办公', description: '美团AI服务', isFree: true },
  { name: '饿了么AI', website: 'https://www.ele.me', category: 'AI办公', description: '饿了么AI推荐', isFree: true },
  
  // === AI工具 - 旅游 ===
  { name: '携程AI', website: 'https://www.ctrip.com', category: 'AI办公', description: '携程AI出行助手', isFree: true },
  { name: '飞猪AI', website: 'https://www.fliggy.com', category: 'AI办公', description: '飞猪AI旅游服务', isFree: true },
  { name: '去哪儿AI', website: 'https://www.qunar.com', category: 'AI办公', description: '去哪儿AI助手', isFree: true },
  { name: '马蜂窝AI', website: 'https://www.mafengwo.cn', category: 'AI办公', description: '马蜂窝AI旅游', isFree: true },
  { name: '途牛AI', website: 'https://www.tuniu.com', category: 'AI办公', description: '途牛AI出行', isFree: true },
  { name: '同程AI', website: 'https://www.ly.com', category: 'AI办公', description: '同程AI旅游', isFree: true },
  { name: '高德AI', website: 'https://www.amap.com', category: 'AI办公', description: '高德AI导航', isFree: true },
  { name: '百度地图AI', website: 'https://map.baidu.com', category: 'AI办公', description: '百度地图AI功能', isFree: true },
  { name: '滴滴AI', website: 'https://www.didiglobal.com', category: 'AI办公', description: '滴滴AI出行', isFree: true },
  { name: '嘀嗒出行AI', website: 'https://www.didapinche.com', category: 'AI办公', description: '嘀嗒AI顺风车', isFree: true },
  
  // === AI工具 - 房产 ===
  { name: '链家AI', website: 'https://www.lianjia.com', category: 'AI办公', description: '链家AI找房', isFree: true },
  { name: '贝壳找房AI', website: 'https://www.ke.com', category: 'AI办公', description: '贝壳AI看房', isFree: true },
  { name: '安居客AI', website: 'https://www.anjuke.com', category: 'AI办公', description: '安居客AI找房', isFree: true },
  { name: '58同城AI', website: 'https://www.58.com', category: 'AI办公', description: '58AI分类信息', isFree: true },
  { name: '自如AI', website: 'https://www.ziroom.com', category: 'AI办公', description: '自如AI租房', isFree: true },
  
  // === AI工具 - 求职招聘 ===
  { name: 'BOSS直聘AI', website: 'https://www.zhipin.com', category: 'AI办公', description: 'BOSS直聘AI推荐', isFree: true },
  { name: '猎聘AI', website: 'https://www.liepin.com', category: 'AI办公', description: '猎聘AI求职', isFree: true },
  { name: '智联招聘AI', website: 'https://www.zhaopin.com', category: 'AI办公', description: '智联AI招聘', isFree: true },
  { name: '拉勾AI', website: 'https://www.lagou.com', category: 'AI办公', description: '拉勾AI求职', isFree: true },
  { name: '脉脉AI', website: 'https://maimai.cn', category: 'AI办公', description: '脉脉AI职场社交', isFree: true },
  { name: '领英中国', website: 'https://www.linkedin.cn', category: 'AI办公', description: '领英职场社交', isFree: true },
  
  // === AI工具 - 社交 ===
  { name: '微信AI', website: 'https://weixin.qq.com', category: 'AI对话', description: '微信AI功能', isFree: true },
  { name: 'QQ AI', website: 'https://im.qq.com', category: 'AI对话', description: 'QQ AI功能', isFree: true },
  { name: '微博AI', website: 'https://weibo.com', category: 'AI写作', description: '微博AI内容', isFree: true },
  { name: '知乎AI', website: 'https://www.zhihu.com', category: 'AI对话', description: '知乎AI问答', isFree: true },
  { name: '豆瓣AI', website: 'https://www.douban.com', category: 'AI对话', description: '豆瓣AI推荐', isFree: true },
  { name: '贴吧AI', website: 'https://tieba.baidu.com', category: 'AI对话', description: '百度贴吧AI', isFree: true },
  
  // === AI工具 - 创意设计 ===
  { name: '稿定设计', website: 'https://www.gaoding.com', category: 'AI绘画', description: '在线设计平台', isFree: true },
  { name: '创客贴', website: 'https://www.chuangkit.com', category: 'AI绘画', description: '在线设计工具', isFree: true },
  { name: '图怪兽', website: 'https://818ps.com', category: 'AI绘画', description: '在线设计平台', isFree: true },
  { name: 'Canva可画', website: 'https://www.canva.cn', category: 'AI绘画', description: '在线设计工具', isFree: true },
  { name: 'Figma中文', website: 'https://www.figma.com', category: 'AI办公', description: '在线设计协作工具', isFree: true },
  { name: '即时设计', website: 'https://js.design', category: 'AI办公', description: '在线UI设计工具', isFree: true },
  { name: 'MasterGo', website: 'https://mastergo.com', category: 'AI办公', description: '在线设计平台', isFree: true },
  { name: 'Pixso', website: 'https://pixso.cn', category: 'AI办公', description: '设计协作平台', isFree: true },
  
  // === AI工具 - 效率工具 ===
  { name: '讯飞语记', website: 'https://www.iyuji.cn', category: 'AI办公', description: 'AI语音笔记', isFree: true },
  { name: '有道云笔记', website: 'https://note.youdao.com', category: 'AI办公', description: '云笔记AI功能', isFree: true },
  { name: '印象笔记', website: 'https://www.yinxiang.com', category: 'AI办公', description: '笔记AI助手', isFree: true },
  { name: '为知笔记', website: 'https://www.wiz.cn', category: 'AI办公', description: '笔记AI功能', isFree: true },
  { name: 'Notion中文', website: 'https://www.notion.so', category: 'AI办公', description: '笔记协作AI', isFree: true },
  { name: '我来', website: 'https://www.wolai.com', category: 'AI办公', description: 'AI笔记工具', isFree: true },
  { name: 'FlowUs息流', website: 'https://flowus.cn', category: 'AI办公', description: 'AI知识库', isFree: true },
  { name: '思源笔记', website: 'https://b3log.org/siyuan', category: 'AI办公', description: '本地笔记AI', isFree: true },
  { name: 'Logseq中文', website: 'https://logseq.com', category: 'AI办公', description: '双向链接笔记', isFree: true },
  { name: 'Obsidian中文', website: 'https://obsidian.md', category: 'AI办公', description: '知识管理工具', isFree: true },
  
  // === AI工具 - 翻译 ===
  { name: '百度翻译', website: 'https://fanyi.baidu.com', category: 'AI学习', description: '百度AI翻译服务', isFree: true },
  { name: '有道翻译', website: 'https://fanyi.youdao.com', category: 'AI学习', description: '网易有道翻译', isFree: true },
  { name: '腾讯翻译君', website: 'https://fanyi.qq.com', category: 'AI学习', description: '腾讯AI翻译', isFree: true },
  { name: 'DeepL中文', website: 'https://www.deepl.com/zh', category: 'AI学习', description: '高质量AI翻译', isFree: true },
  { name: '谷歌翻译', website: 'https://translate.google.cn', category: 'AI学习', description: '谷歌翻译服务', isFree: true },
  { name: '必应翻译', website: 'https://www.bing.com/translator', category: 'AI学习', description: '微软翻译服务', isFree: true },
  { name: '金山词霸', website: 'https://www.iciba.com', category: 'AI学习', description: 'AI词典翻译', isFree: true },
  { name: '海词词典', website: 'https://dict.cn', category: 'AI学习', description: '在线词典AI', isFree: true },
  
  // === AI工具 - 浏览器AI ===
  { name: '夸克AI', website: 'https://www.myquark.cn', category: 'AI对话', description: '夸克浏览器AI助手', isFree: true },
  { name: 'QQ浏览器AI', website: 'https://browser.qq.com', category: 'AI对话', description: 'QQ浏览器AI功能', isFree: true },
  { name: 'UC浏览器AI', website: 'https://www.uc.cn', category: 'AI对话', description: 'UC浏览器AI助手', isFree: true },
  { name: '百度App AI', website: 'https://www.baidu.com', category: 'AI对话', description: '百度App AI助手', isFree: true },
  { name: '搜狗搜索AI', website: 'https://www.sogou.com', category: 'AI对话', description: '搜狗AI搜索', isFree: true },
  { name: '360搜索AI', website: 'https://www.so.com', category: 'AI对话', description: '360AI搜索', isFree: true },
  
  // === AI工具 - 企业服务 ===
  { name: '企业微信AI', website: 'https://work.weixin.qq.com', category: 'AI办公', description: '企业微信AI功能', isFree: true },
  { name: '钉钉AI', website: 'https://www.dingtalk.com', category: 'AI办公', description: '钉钉AI助手', isFree: true },
  { name: '飞书AI', website: 'https://www.feishu.cn', category: 'AI办公', description: '飞书AI办公', isFree: true },
  { name: '华为WeLink', website: 'https://www.huaweicloud.com/product/welink.html', category: 'AI办公', description: '华为企业协作', isFree: false },
  { name: '用友AI', website: 'https://www.yonyou.com', category: 'AI办公', description: '用友企业AI服务', isFree: false },
  { name: '金蝶AI', website: 'https://www.kingdee.com', category: 'AI办公', description: '金蝶企业AI', isFree: false },
  { name: '明道云AI', website: 'https://www.mingdao.com', category: 'AI办公', description: '零代码平台AI', isFree: false },
  { name: '简道云AI', website: 'https://www.jiandaoyun.com', category: 'AI办公', description: '零代码AI功能', isFree: true },
  { name: '泛微AI', website: 'https://www.weaver.com.cn', category: 'AI办公', description: 'OA系统AI功能', isFree: false },
  { name: '致远AI', website: 'https://www.seeyon.com', category: 'AI办公', description: '协同办公AI', isFree: false },
  { name: '蓝凌AI', website: 'https://www.landray.com.cn', category: 'AI办公', description: '企业OA AI', isFree: false },
  
  // === 更多AI编程工具 ===
  { name: 'CSDN AI', website: 'https://www.csdn.com', category: 'AI编程', description: '开发者社区AI功能', isFree: true },
  { name: '掘金AI', website: 'https://juejin.cn', category: 'AI编程', description: '技术社区AI助手', isFree: true },
  { name: 'SegmentFault AI', website: 'https://segmentfault.com', category: 'AI编程', description: '技术问答AI', isFree: true },
  { name: 'Stack Overflow中文', website: 'https://stackoverflow.com', category: 'AI编程', description: '程序员问答社区', isFree: true },
  { name: 'GitHub中文', website: 'https://github.com', category: 'AI编程', description: '代码托管平台', isFree: true },
  { name: 'Gitee', website: 'https://gitee.com', category: 'AI编程', description: '国内代码托管平台', isFree: true },
  { name: 'GitLab中文', website: 'https://gitlab.cn', category: 'AI编程', description: '代码托管平台', isFree: true },
  { name: 'Coding.net', website: 'https://coding.net', category: 'AI编程', description: '云端开发平台', isFree: true },
  { name: '华为云DevCloud', website: 'https://www.huaweicloud.com/devcloud', category: 'AI编程', description: '华为云开发平台', isFree: false },
  { name: '阿里云云效', website: 'https://www.aliyun.com/product/yunxiao', category: 'AI编程', description: '阿里云开发平台', isFree: false },
  { name: '腾讯云Coding', website: 'https://coding.net', category: 'AI编程', description: '腾讯云开发工具', isFree: true },
  
  // === AI工具 - 起名 ===
  { name: '起名通AI', website: 'https://www.qimingtong.com', category: 'AI写作', description: 'AI智能起名', isFree: true },
  { name: '名字打分AI', website: 'https://www.name161.com', category: 'AI写作', description: 'AI姓名评测', isFree: true },
  { name: '公司起名AI', website: 'https://www.gongsiqiming.com', category: 'AI写作', description: 'AI公司起名', isFree: true },
  { name: '宝宝起名AI', website: 'https://www.baobaoqiming.com', category: 'AI写作', description: 'AI宝宝起名', isFree: true },
  
  // === AI工具 - 图像处理 ===
  { name: '佐糖', website: 'https://picwish.cn', category: 'AI绘画', description: 'AI图像处理工具', isFree: true },
  { name: ' VanceAI中文', website: 'https://vanceai.com', category: 'AI绘画', description: 'AI图像增强', isFree: false },
  { name: 'Pixelcut中文', website: 'https://www.pixelcut.ai', category: 'AI绘画', description: 'AI图片编辑', isFree: true },
  { name: 'PhotoRoom中文', website: 'https://www.photoroom.com', category: 'AI绘画', description: 'AI背景移除', isFree: true },
  { name: 'Clipdrop中文', website: 'https://clipdrop.co', category: 'AI绘画', description: 'AI图像工具集', isFree: true },
  { name: 'LetsEnhance中文', website: 'https://letsenhance.io', category: 'AI绘画', description: 'AI图片放大', isFree: true },
  { name: 'BigJPG', website: 'https://bigjpg.com', category: 'AI绘画', description: 'AI图片无损放大', isFree: true },
  { name: 'waifu2x', website: 'https://waifu2x.udp.jp', category: 'AI绘画', description: 'AI动漫图片放大', isFree: true },
  
  // === AI工具 - 人脸识别 ===
  { name: '旷视Face++', website: 'https://www.faceplusplus.com.cn', category: 'AI绘画', description: '人脸识别API', isFree: false },
  { name: '百度人脸识别', website: 'https://cloud.baidu.com/product/face', category: 'AI绘画', description: '百度人脸AI', isFree: false },
  { name: '腾讯云人脸', website: 'https://cloud.tencent.com/product/facerecognition', category: 'AI绘画', description: '腾讯人脸识别', isFree: false },
  { name: '阿里云人脸', website: 'https://www.aliyun.com/product/face', category: 'AI绘画', description: '阿里人脸识别', isFree: false },
  { name: 'Face++', website: 'https://www.faceplusplus.com.cn', category: 'AI绘画', description: '旷视人脸AI平台', isFree: false },
  
  // === AI工具 - 自动驾驶 ===
  { name: '百度Apollo', website: 'https://apollo.baidu.com', category: 'AI编程', description: '百度自动驾驶平台', isFree: false },
  { name: '小鹏自动驾驶', website: 'https://www.xiaopeng.com', category: 'AI编程', description: '小鹏自动驾驶技术', isFree: false },
  { name: '蔚来自动驾驶', website: 'https://www.nio.com', category: 'AI编程', description: '蔚来自动驾驶', isFree: false },
  { name: '理想自动驾驶', website: 'https://www.lixiang.com', category: 'AI编程', description: '理想智能驾驶', isFree: false },
  { name: '华为ADS', website: 'https://consumer.huawei.com/cn', category: 'AI编程', description: '华为自动驾驶', isFree: false },
  { name: '地平线', website: 'https://www.horizon.ai', category: 'AI编程', description: '自动驾驶芯片', isFree: false },
  { name: '小马智行', website: 'https://www.pony.ai', category: 'AI编程', description: '自动驾驶技术', isFree: false },
  { name: '文远知行', website: 'https://www.weride.ai', category: 'AI编程', description: '自动驾驶公司', isFree: false },
  { name: 'AutoX', website: 'https://www.autox.ai', category: 'AI编程', description: '无人驾驶技术', isFree: false },
  { name: 'Momenta', website: 'https://www.momenta.ai', category: 'AI编程', description: '自动驾驶AI', isFree: false },
  
  // === AI工具 - 智能硬件 ===
  { name: '小度智能音箱', website: 'https://xiaodu.baidu.com', category: 'AI对话', description: '百度智能音箱', isFree: true },
  { name: '天猫精灵', website: 'https://www.tmallgenie.com', category: 'AI对话', description: '阿里智能音箱', isFree: true },
  { name: '小爱音箱', website: 'https://xiaoai.mi.com', category: 'AI对话', description: '小米智能音箱', isFree: true },
  { name: '小度在家', website: 'https://xiaodu.baidu.com', category: 'AI对话', description: '百度智能屏', isFree: true },
  { name: '华为智能音箱', website: 'https://consumer.huawei.com/cn', category: 'AI对话', description: '华为AI音箱', isFree: true },
  
  // === AI工具 - 更多对话 ===
  { name: 'AI地球', website: 'https://www.aiearth.com', category: 'AI对话', description: 'AI对话助手', isFree: true },
  { name: 'ChatGLM', website: 'https://chatglm.cn', category: 'AI对话', description: '智谱AI对话', isFree: true },
  { name: 'MOSS', website: 'https://moss.fastai.cn', category: 'AI对话', description: '复旦开源对话模型', isFree: true },
  { name: '讯飞星火APP', website: 'https://xinghuo.xfyun.cn', category: 'AI对话', description: '讯飞星火移动端', isFree: true },
  { name: '通义千问APP', website: 'https://tongyi.aliyun.com/app', category: 'AI对话', description: '通义千问移动版', isFree: true },
  { name: 'Kimi APP', website: 'https://kimi.moonshot.cn', category: 'AI对话', description: 'Kimi移动端', isFree: true },
  { name: '豆包APP', website: 'https://www.doubao.com/app', category: 'AI对话', description: '豆包移动应用', isFree: true },
  { name: '文心一言APP', website: 'https://yiyan.baidu.com/app', category: 'AI对话', description: '文心一言移动版', isFree: true },
  
  // === AI工具 - 数据标注 ===
  { name: '标贝数据', website: 'https://www.data-baker.com', category: 'AI编程', description: 'AI数据标注服务', isFree: false },
  { name: '云测数据', website: 'https://www.testin.cn', category: 'AI编程', description: '数据标注平台', isFree: false },
  { name: '倍赛数据', website: 'https://www.basicfinder.com', category: 'AI编程', description: 'AI数据服务', isFree: false },
  { name: '海天瑞声', website: 'https://www.haitianruisheng.com', category: 'AI编程', description: 'AI训练数据', isFree: false },
  
  // === AI工具 - 网络安全 ===
  { name: '360安全AI', website: 'https://www.360.cn', category: 'AI办公', description: '360安全AI服务', isFree: true },
  { name: '腾讯安全AI', website: 'https://s.tencent.com', category: 'AI办公', description: '腾讯安全AI', isFree: false },
  { name: '阿里云安全AI', website: 'https://www.aliyun.com/product/security', category: 'AI办公', description: '阿里云安全', isFree: false },
  { name: '深信服AI', website: 'https://www.sangfor.com.cn', category: 'AI办公', description: '网络安全AI', isFree: false },
  { name: '奇安信AI', website: 'https://www.qianxin.com', category: 'AI办公', description: '网络安全AI', isFree: false },
  
  // === AI工具 - 物流 ===
  { name: '菜鸟AI', website: 'https://www.cainiao.com', category: 'AI办公', description: '菜鸟物流AI', isFree: false },
  { name: '京东物流AI', website: 'https://www.jdl.com', category: 'AI办公', description: '京东智能物流', isFree: false },
  { name: '顺丰AI', website: 'https://www.sf-express.com', category: 'AI办公', description: '顺丰智能物流', isFree: false },
  { name: '中通AI', website: 'https://www.zto.com', category: 'AI办公', description: '中通物流AI', isFree: false },
  { name: '韵达AI', website: 'https://www.yundaex.com', category: 'AI办公', description: '韵达物流AI', isFree: false },
  
  // === AI工具 - 金融 ===
  { name: '蚂蚁金服AI', website: 'https://www.antgroup.com', category: 'AI办公', description: '蚂蚁AI金融', isFree: false },
  { name: '京东数科AI', website: 'https://www.jdd.com', category: 'AI办公', description: '京东AI金融', isFree: false },
  { name: '度小满AI', website: 'https://www.duxiaoman.com', category: 'AI办公', description: '百度AI金融', isFree: false },
  { name: '平安金融AI', website: 'https://www.pingan.com', category: 'AI办公', description: '平安AI服务', isFree: false },
  { name: '招商银行AI', website: 'https://www.cmbchina.com', category: 'AI办公', description: '招行AI服务', isFree: true },
  
  // === AI工具 - 区块链 ===
  { name: '蚂蚁链AI', website: 'https://www.antchain.antgroup.com', category: 'AI编程', description: '蚂蚁区块链AI', isFree: false },
  { name: '腾讯区块链AI', website: 'https://trustsql.qq.com', category: 'AI编程', description: '腾讯区块链', isFree: false },
  { name: '百度超级链', website: 'https://xuper.baidu.com', category: 'AI编程', description: '百度区块链', isFree: false },
  
  // === AI工具 - 云计算 ===
  { name: '阿里云AI', website: 'https://www.aliyun.com/product/ai', category: 'AI编程', description: '阿里云AI服务', isFree: false },
  { name: '腾讯云AI', website: 'https://cloud.tencent.com/product/ai', category: 'AI编程', description: '腾讯云AI服务', isFree: false },
  { name: '华为云AI', website: 'https://www.huaweicloud.com/product/ai.html', category: 'AI编程', description: '华为云AI服务', isFree: false },
  { name: '百度智能云AI', website: 'https://cloud.baidu.com/product/ai', category: 'AI编程', description: '百度云AI服务', isFree: false },
  { name: '京东云AI', website: 'https://www.jdcloud.com/cn/products', category: 'AI编程', description: '京东云AI服务', isFree: false },
  { name: '火山引擎AI', website: 'https://www.volcengine.com', category: 'AI编程', description: '字节云AI服务', isFree: false },
  
  // === AI工具 - 更多写作 ===
  { name: '讯飞公文写作', website: 'https://gongwen.iflytek.com', category: 'AI写作', description: 'AI公文写作平台', isFree: true },
  { name: '写作猫', website: 'https://xiezuocat.com', category: 'AI写作', description: 'AI写作助手', isFree: true },
  { name: '笔杆子AI', website: 'https://www.biganshipin.com', category: 'AI写作', description: '公文写作AI', isFree: true },
  { name: '写作助手', website: 'https://www.xiezuo.life', category: 'AI写作', description: 'AI写作工具', isFree: true },
  { name: '文案狗', website: 'https://www.wenangou.com', category: 'AI写作', description: 'AI文案生成', isFree: true },
  { name: '句子控', website: 'https://www.juzikong.com', category: 'AI写作', description: 'AI句子生成', isFree: true },
  
  // === AI工具 - 更多学习 ===
  { name: '猿辅导AI', website: 'https://www.yuanfudao.com', category: 'AI学习', description: '猿辅导在线教育', isFree: true },
  { name: '高途AI', website: 'https://www.gaotu.cn', category: 'AI学习', description: '高途在线教育', isFree: true },
  { name: '网易有道AI', website: 'https://www.youdao.com', category: 'AI学习', description: '有道AI教育', isFree: true },
  { name: '一起教育AI', website: 'https://www.17zuoye.com', category: 'AI学习', description: '一起作业AI', isFree: true },
  { name: '洋葱学园AI', website: 'https://www.yangcong345.com', category: 'AI学习', description: '洋葱AI学习', isFree: true },
  { name: '乐乐课堂AI', website: 'https://www.leleketang.com', category: 'AI学习', description: '乐乐AI课堂', isFree: true },
  { name: '学霸君AI', website: 'https://www.xueba100.com', category: 'AI学习', description: '学霸君AI辅导', isFree: true },
  { name: '掌门教育AI', website: 'https://www.zhangmen.com', category: 'AI学习', description: '掌门AI教育', isFree: true },
  
  // === AI工具 - 儿童教育 ===
  { name: '凯叔讲故事AI', website: 'https://www.kaishustory.com', category: 'AI学习', description: '凯叔AI故事', isFree: true },
  { name: '叽里呱啦AI', website: 'https://www.jiliguala.com', category: 'AI学习', description: '儿童英语AI', isFree: true },
  { name: '伴鱼绘本AI', website: 'https://www.ipalmap.com', category: 'AI学习', description: 'AI绘本阅读', isFree: true },
  { name: '洪恩识字AI', website: 'https://www.hongen.com', category: 'AI学习', description: 'AI识字教育', isFree: true },
  { name: '宝宝巴士AI', website: 'https://www.babybus.com', category: 'AI学习', description: '宝宝巴士AI', isFree: true },
  
  // === AI工具 - 体育健身 ===
  { name: 'Keep AI', website: 'https://www.gotokeep.com', category: 'AI学习', description: 'AI健身教练', isFree: true },
  { name: '咕咚AI', website: 'https://www.codoon.com', category: 'AI学习', description: 'AI运动助手', isFree: true },
  { name: '悦跑圈AI', website: 'https://www.thejoyrun.com', category: 'AI学习', description: 'AI跑步助手', isFree: true },
  { name: '薄荷健康AI', website: 'https://www.boohee.com', category: 'AI学习', description: 'AI健康管理', isFree: true },
  
  // === AI工具 - 新闻资讯 ===
  { name: '今日头条AI', website: 'https://www.toutiao.com', category: 'AI对话', description: '头条AI推荐', isFree: true },
  { name: '澎湃新闻AI', website: 'https://www.thepaper.cn', category: 'AI写作', description: '澎湃AI新闻', isFree: true },
  { name: '界面新闻AI', website: 'https://www.jiemian.com', category: 'AI写作', description: '界面AI内容', isFree: true },
  { name: '36氪AI', website: 'https://36kr.com', category: 'AI写作', description: '36氪AI科技', isFree: true },
  { name: '虎嗅AI', website: 'https://www.huxiu.com', category: 'AI写作', description: '虎嗅AI科技', isFree: true },
  { name: '钛媒体AI', website: 'https://www.tmtpost.com', category: 'AI写作', description: '钛媒体AI', isFree: true },
  
  // === AI工具 - 购物比价 ===
  { name: '什么值得买AI', website: 'https://www.smzdm.com', category: 'AI办公', description: 'AI购物推荐', isFree: true },
  { name: '慢慢买AI', website: 'https://www.manmanbuy.com', category: 'AI办公', description: 'AI比价工具', isFree: true },
  { name: '惠惠购物AI', website: 'https://www.huihui.cn', category: 'AI办公', description: 'AI比价助手', isFree: true },
  { name: '一淘AI', website: 'https://www.etao.com', category: 'AI办公', description: '阿里比价平台', isFree: true },
  
  // === AI工具 - 本地生活 ===
  { name: '大众点评AI', website: 'https://www.dianping.com', category: 'AI办公', description: '点评AI推荐', isFree: true },
  { name: '口碑AI', website: 'https://www.koubei.com', category: 'AI办公', description: '口碑AI服务', isFree: true },
  { name: '美团外卖AI', website: 'https://www.meituan.com/waimai', category: 'AI办公', description: '外卖AI推荐', isFree: true },
  { name: '饿了么AI', website: 'https://www.ele.me', category: 'AI办公', description: '饿了么AI', isFree: true },
  
  // === AI工具 - 二手交易 ===
  { name: '闲鱼AI', website: 'https://www.goofish.com', category: 'AI办公', description: '闲鱼AI交易', isFree: true },
  { name: '转转AI', website: 'https://www.zhuanzhuan.com', category: 'AI办公', description: '转转AI估价', isFree: true },
  { name: '爱回收AI', website: 'https://www.aihuishou.com', category: 'AI办公', description: 'AI二手回收', isFree: true },
  
  // === AI工具 - 婚恋交友 ===
  { name: '陌陌AI', website: 'https://www.immomo.com', category: 'AI对话', description: '陌陌AI匹配', isFree: true },
  { name: '探探AI', website: 'https://wwwtantanapp.com', category: 'AI对话', description: '探探AI推荐', isFree: true },
  { name: 'Soul AI', website: 'https://www.soulapp.cn', category: 'AI对话', description: 'Soul AI社交', isFree: true },
  { name: '百合网AI', website: 'https://www.baihe.com', category: 'AI对话', description: '百合AI婚恋', isFree: true },
  { name: '世纪佳缘AI', website: 'https://www.jiayuan.com', category: 'AI对话', description: '佳缘AI匹配', isFree: true },
  
  // === AI工具 - 生活服务 ===
  { name: '58到家AI', website: 'https://www.daojia.com', category: 'AI办公', description: '到家AI服务', isFree: true },
  { name: '河狸家AI', website: 'https://www.helijia.com', category: 'AI办公', description: '美业AI服务', isFree: true },
  { name: '美团打车AI', website: 'https://www.meituan.com/dache', category: 'AI办公', description: '打车AI服务', isFree: true },
  { name: '嘀嗒出行AI', website: 'https://www.didapinche.com', category: 'AI办公', description: '嘀嗒AI顺风车', isFree: true },
  
  // === AI工具 - 更多视频 ===
  { name: '哔哩哔哩', website: 'https://www.bilibili.com', category: 'AI视频', description: 'B站视频平台', isFree: true },
  { name: '优酷AI', website: 'https://www.youku.com', category: 'AI视频', description: '优酷AI推荐', isFree: true },
  { name: '爱奇艺AI', website: 'https://www.iqiyi.com', category: 'AI视频', description: '爱奇艺AI', isFree: true },
  { name: '腾讯视频AI', website: 'https://v.qq.com', category: 'AI视频', description: '腾讯AI视频', isFree: true },
  { name: '芒果TV AI', website: 'https://www.mgtv.com', category: 'AI视频', description: '芒果AI推荐', isFree: true },
  { name: '西瓜视频AI', website: 'https://www.ixigua.com', category: 'AI视频', description: '西瓜AI推荐', isFree: true },
  { name: '抖音', website: 'https://www.douyin.com', category: 'AI视频', description: '抖音短视频平台', isFree: true },
  { name: '快手', website: 'https://www.kuaishou.com', category: 'AI视频', description: '快手短视频平台', isFree: true },
  { name: '视频号', website: 'https://weixin.qq.com', category: 'AI视频', description: '微信视频号', isFree: true },
  { name: '小红书', website: 'https://www.xiaohongshu.com', category: 'AI视频', description: '小红书短视频', isFree: true },
  
  // === AI工具 - 游戏娱乐 ===
  { name: '王者荣耀AI', website: 'https://pvp.qq.com', category: 'AI对话', description: '王者AI对战', isFree: true },
  { name: '和平精英AI', website: 'https://gp.qq.com', category: 'AI对话', description: '吃鸡AI训练', isFree: true },
  { name: '原神AI', website: 'https://ys.mihoyo.com', category: 'AI对话', description: '原神AI助手', isFree: true },
  { name: '米哈游AI', website: 'https://www.mihoyo.com', category: 'AI绘画', description: '米哈游AI美术', isFree: false },
  { name: '网易游戏AI', website: 'https://game.163.com', category: 'AI对话', description: '网易游戏AI', isFree: true },
  { name: '斗鱼AI', website: 'https://www.douyu.com', category: 'AI视频', description: '斗鱼直播AI', isFree: true },
  { name: '虎牙AI', website: 'https://www.huya.com', category: 'AI视频', description: '虎牙直播AI', isFree: true },
  { name: 'YY直播AI', website: 'https://www.yy.com', category: 'AI视频', description: 'YY直播AI', isFree: true },
  
  // === AI工具 - 更多音乐 ===
  { name: '网易云音乐', website: 'https://music.163.com', category: 'AI音频', description: '网易云AI推荐', isFree: true },
  { name: 'QQ音乐', website: 'https://y.qq.com', category: 'AI音频', description: 'QQ音乐AI', isFree: true },
  { name: '酷狗音乐', website: 'https://www.kugou.com', category: 'AI音频', description: '酷狗AI音乐', isFree: true },
  { name: '酷我音乐', website: 'https://www.kuwo.cn', category: 'AI音频', description: '酷我AI音乐', isFree: true },
  { name: '虾米音乐', website: 'https://www.xiami.com', category: 'AI音频', description: '虾米AI音乐', isFree: true },
  
  // === AI工具 - 儿童内容 ===
  { name: '小伴龙AI', website: 'https://www.xiaobanlong.com', category: 'AI学习', description: '儿童AI伙伴', isFree: true },
  { name: '口袋故事AI', website: 'https://www.idaddy.cn', category: 'AI学习', description: 'AI故事平台', isFree: true },
  { name: '喜马拉雅儿童AI', website: 'https://www.ximalaya.com/ertong', category: 'AI学习', description: '儿童AI音频', isFree: true },
  { name: '蜻蜓FM儿童AI', website: 'https://www.qingting.fm', category: 'AI学习', description: '儿童AI内容', isFree: true },
  
  // === AI工具 - 出行导航 ===
  { name: '高德地图', website: 'https://www.amap.com', category: 'AI办公', description: '高德AI导航', isFree: true },
  { name: '百度地图', website: 'https://map.baidu.com', category: 'AI办公', description: '百度AI地图', isFree: true },
  { name: '腾讯地图', website: 'https://map.qq.com', category: 'AI办公', description: '腾讯AI地图', isFree: true },
  { name: '搜狗地图', website: 'https://map.sogou.com', category: 'AI办公', description: '搜狗AI地图', isFree: true },
  
  // === AI工具 - 阅读小说 ===
  { name: '起点中文网AI', website: 'https://www.qidian.com', category: 'AI写作', description: '起点AI推荐', isFree: true },
  { name: '晋江文学城AI', website: 'https://www.jjwxc.net', category: 'AI写作', description: '晋江AI推荐', isFree: true },
  { name: '纵横中文网AI', website: 'https://www.zongheng.com', category: 'AI写作', description: '纵横AI推荐', isFree: true },
  { name: '番茄小说AI', website: 'https://www.fanqienovel.com', category: 'AI写作', description: '番茄AI小说', isFree: true },
  { name: '七猫小说AI', website: 'https://www.qimao.com', category: 'AI写作', description: '七猫AI推荐', isFree: true },
  { name: 'QQ阅读AI', website: 'https://reader.qq.com', category: 'AI写作', description: 'QQ阅读AI', isFree: true },
  { name: '微信读书AI', website: 'https://weread.qq.com', category: 'AI学习', description: '微信读书AI', isFree: true },
  { name: '掌阅AI', website: 'https://www.ireader.com', category: 'AI学习', description: '掌阅AI推荐', isFree: true },
  { name: '书旗小说AI', website: 'https://www.shuqi.com', category: 'AI写作', description: '书旗AI推荐', isFree: true },
  { name: '连尚读书AI', website: 'https://www.lianshangdushu.com', category: 'AI学习', description: '连尚AI阅读', isFree: true },
  
  // === 更多AI工具 ===
  { name: '数美智能', website: 'https://www.ishumei.com', category: 'AI办公', description: 'AI内容安全风控', isFree: false },
  { name: '网易易盾AI', website: 'https://dun.163.com/ai', category: 'AI办公', description: '网易内容安全AI', isFree: false },
  { name: '阿里绿网', website: 'https://www.aliyun.com/product/green', category: 'AI办公', description: '阿里云内容安全', isFree: false },
  { name: '腾讯天御', website: 'https://cloud.tencent.com/product/gs', category: 'AI办公', description: '腾讯业务安全AI', isFree: false },
  { name: '百度内容审核', website: 'https://cloud.baidu.com/product/censor.html', category: 'AI办公', description: '百度AI内容审核', isFree: false },
  { name: '华为内容安全', website: 'https://www.huaweicloud.com/product/ecs', category: 'AI办公', description: '华为云内容审核', isFree: false },
  { name: '七牛内容审核', website: 'https://www.qiniu.com/products/censor', category: 'AI办公', description: '七牛内容审核AI', isFree: false },
  { name: '又拍云审核', website: 'https://www.upyun.com/products/censor', category: 'AI办公', description: '又拍云内容审核', isFree: false },
  { name: '金山云审核', website: 'https://www.ksyun.com/products/censor', category: 'AI办公', description: '金山云内容审核', isFree: false },
  { name: '网宿安全', website: 'https://www.wangsu.com', category: 'AI办公', description: '网宿CDN安全AI', isFree: false },
  { name: '白山云安全', website: 'https://www.baishan.com', category: 'AI办公', description: '白山云安全服务', isFree: false },
  { name: '帝联云安全', website: 'https://www.dnion.com', category: 'AI办公', description: '帝联CDN安全', isFree: false },
  { name: '同盾科技', website: 'https://www.tongdun.cn', category: 'AI办公', description: 'AI风控服务', isFree: false },
  { name: '邦盛科技', website: 'https://www.bsfit.cn', category: 'AI办公', description: '金融风控AI', isFree: false },
  { name: '冰鉴科技', website: 'https://www.icekredit.com', category: 'AI办公', description: 'AI信用评估', isFree: false },
  { name: '百融云创', website: 'https://www.100credit.com', category: 'AI办公', description: 'AI风控服务', isFree: false },
  { name: '顶象技术', website: 'https://www.dingxiang-inc.com', category: 'AI办公', description: 'AI反欺诈服务', isFree: false },
  { name: '极验验证', website: 'https://www.geetest.com', category: 'AI办公', description: 'AI验证码服务', isFree: false },
  { name: '网易易盾验证', website: 'https://dun.163.com/product/captcha', category: 'AI办公', description: '网易智能验证', isFree: false },
  { name: '腾讯验证码', website: 'https://cloud.tencent.com/product/captcha', category: 'AI办公', description: '腾讯AI验证码', isFree: false },
  { name: '阿里云验证码', website: 'https://www.aliyun.com/product/captcha', category: 'AI办公', description: '阿里智能验证', isFree: false },
  { name: '行为验证AI', website: 'https://www.behavsec.com', category: 'AI办公', description: '行为验证安全', isFree: false },
  { name: '云片短信AI', website: 'https://www.yunpian.com', category: 'AI办公', description: '智能短信服务', isFree: false },
  { name: '容联云通讯AI', website: 'https://www.yuntongxun.com/ai', category: 'AI办公', description: '智能通讯服务', isFree: false },
  { name: '梦网云通讯', website: 'https://www.montnets.com', category: 'AI办公', description: '企业云通讯AI', isFree: false },
  { name: '创蓝云智', website: 'https://www.chuanglan.com', category: 'AI办公', description: '智能短信平台', isFree: false },
  { name: '亿美软通', website: 'https://www.emay.cn', category: 'AI办公', description: '移动商务AI', isFree: false },
  { name: '漫道科技', website: 'https://www.zucp.net', category: 'AI办公', description: '短信平台AI', isFree: false },
  { name: '大汉三通', website: 'https://www.dahantc.com', category: 'AI办公', description: '云通讯AI服务', isFree: false },
  { name: '信通时代', website: 'https://www.xintongtimes.com', category: 'AI办公', description: '通讯平台AI', isFree: false },
  { name: '云之讯', website: 'https://www.yunzhixun.com', category: 'AI办公', description: '云通讯服务', isFree: false },
  { name: '容联七陌', website: 'https://www.7moor.com', category: 'AI办公', description: '智能客服系统', isFree: false },
  { name: '天润融通', website: 'https://www.ti-net.com', category: 'AI办公', description: '呼叫中心AI', isFree: false },
  { name: '讯鸟软件', website: 'https://www.infobird.com', category: 'AI办公', description: '智能客服AI', isFree: false },
  { name: '网易七鱼', website: 'https://qiyukf.com', category: 'AI办公', description: '网易智能客服', isFree: false },
  { name: '智齿科技', website: 'https://www.sobot.com', category: 'AI办公', description: 'AI客服平台', isFree: false },
  { name: '美洽', website: 'https://www.meiqia.com', category: 'AI办公', description: '在线客服AI', isFree: false },
  { name: '环信客服', website: 'https://www.easemob.com/product/customer-service', category: 'AI办公', description: '智能客服系统', isFree: false },
  { name: 'Udesk', website: 'https://www.udesk.cn', category: 'AI办公', description: '客服系统AI', isFree: false },
  { name: '逸创云客服', website: 'https://www.kf5.com', category: 'AI办公', description: '云客服平台', isFree: false },
  { name: '合力亿捷', website: 'https://www.hollycrm.com', category: 'AI办公', description: 'CRM客服AI', isFree: false },
  { name: '神州云动', website: 'https://www.cloudcc.com', category: 'AI办公', description: 'CRM AI服务', isFree: false },
  { name: '销售易CRM', website: 'https://www.xiaoshouyi.com', category: 'AI办公', description: '销售AI平台', isFree: false },
  { name: '纷享销客', website: 'https://www.fxiaoke.com', category: 'AI办公', description: 'CRM AI服务', isFree: false },
  { name: '红圈营销', website: 'https://www.hecom.cn', category: 'AI办公', description: '营销AI服务', isFree: false },
  { name: '明源云', website: 'https://www.mingyuanyun.com', category: 'AI办公', description: '地产AI服务', isFree: false },
  { name: '北森云计算', website: 'https://www.beisen.com', category: 'AI办公', description: 'HR SaaS AI', isFree: false },
  { name: '肯耐珂萨', website: 'https://www.knx.com.cn', category: 'AI办公', description: 'HR AI服务', isFree: false },
  { name: '盖雅工场', website: 'https://www.gaiaworks.com', category: 'AI办公', description: '劳动力管理AI', isFree: false },
  { name: '劳动力云AI', website: 'https://www.laowuyun.com', category: 'AI办公', description: '劳动力管理服务', isFree: false },
  { name: '喔趣科技', website: 'https://www.woqu.tech', category: 'AI办公', description: 'HR AI服务', isFree: false },
  { name: '薪人薪事', website: 'https://www.xinrenxinshi.com', category: 'AI办公', description: 'HR SaaS AI', isFree: false },
  { name: '易路软件', website: 'https://www.ersoft.com', category: 'AI办公', description: '薪酬管理AI', isFree: false },
  { name: 'CDP集团', website: 'https://www.cdpgroup.com', category: 'AI办公', description: 'HR服务AI', isFree: false },
  { name: '外勤365', website: 'https://www.waiqin365.com', category: 'AI办公', description: '外勤管理AI', isFree: false },
  { name: '销售罗盘', website: 'https://www.salescompass.cn', category: 'AI办公', description: '销售AI助手', isFree: false },
  { name: '探迹科技', website: 'https://www.tungee.com', category: 'AI办公', description: '智能销售AI', isFree: false },
  { name: '励销云', website: 'https://www.lixiaoyun.com', category: 'AI办公', description: '销售AI平台', isFree: false },
  { name: '加推科技', website: 'https://www.jiatui.com', category: 'AI办公', description: '销售AI工具', isFree: false },
  { name: '卫瓴科技', website: 'https://www.willing-tech.com', category: 'AI办公', description: '协同CRM AI', isFree: false },
  { name: '尘锋SCRM', website: 'https://www.chenfengcrm.com', category: 'AI办公', description: '私域运营AI', isFree: false },
  { name: '群脉SCRM', website: 'https://www.shuwen.com', category: 'AI办公', description: '用户运营AI', isFree: false },
  { name: '有赞AI', website: 'https://www.youzan.com', category: 'AI办公', description: '电商AI服务', isFree: false },
  { name: '微盟AI', website: 'https://www.weimob.com', category: 'AI办公', description: '智慧零售AI', isFree: false },
  { name: '点点客AI', website: 'https://www.dodoca.com', category: 'AI办公', description: '营销AI服务', isFree: false },
  { name: '微店AI', website: 'https://www.weidian.com', category: 'AI办公', description: '电商AI服务', isFree: false },
  { name: '拼多多商家AI', website: 'https://mms.pinduoduo.com', category: 'AI办公', description: '拼多多AI工具', isFree: true },
  { name: '淘宝千牛AI', website: 'https://myseller.taobao.com', category: 'AI办公', description: '淘宝商家AI', isFree: true },
  { name: '京东商家AI', website: 'https://shop.jd.com', category: 'AI办公', description: '京东商家AI', isFree: true },
  { name: '抖音电商AI', website: 'https://fxg.jinritemai.com', category: 'AI办公', description: '抖音商家AI', isFree: true },
  { name: '快手电商AI', website: 'https://s.kwaixiaodian.com', category: 'AI办公', description: '快手商家AI', isFree: true },
  { name: '小红书商家AI', website: 'https://www.xiaohongshu.com/commerce', category: 'AI办公', description: '小红书商家AI', isFree: true },
  { name: '美团商家AI', website: 'https://e.waimai.meituan.com', category: 'AI办公', description: '美团商家AI', isFree: true },
  { name: '饿了么商家AI', website: 'https://open.ele.me', category: 'AI办公', description: '饿了么商家AI', isFree: true },
  { name: '口碑商家AI', website: 'https://b.koubei.com', category: 'AI办公', description: '口碑商家AI', isFree: true },
  { name: '飞猪商家AI', website: 'https://trip.alibaba.com', category: 'AI办公', description: '飞猪商家AI', isFree: true },
  { name: '携程商家AI', website: 'https://openapi.ctrip.com', category: 'AI办公', description: '携程商家AI', isFree: true },
  { name: '去哪儿商家AI', website: 'https://biz.qunar.com', category: 'AI办公', description: '去哪儿商家AI', isFree: true },
  { name: '同程商家AI', website: 'https://www.ly.com/biz', category: 'AI办公', description: '同程商家AI', isFree: true },
  { name: '马蜂窝商家AI', website: 'https://open.mafengwo.cn', category: 'AI办公', description: '马蜂窝商家AI', isFree: true },
  { name: '途牛商家AI', website: 'https://biz.tuniu.com', category: 'AI办公', description: '途牛商家AI', isFree: true },
  { name: '滴滴企业AI', website: 'https://enterprise.didichuxing.com', category: 'AI办公', description: '滴滴企业服务', isFree: false },
  { name: '曹操企业AI', website: 'https://www.caocaokeji.cn', category: 'AI办公', description: '曹操企业服务', isFree: false },
  { name: '神州专车企业AI', website: 'https://www.zuche.com', category: 'AI办公', description: '神州企业服务', isFree: false },
  { name: '首汽约车企业AI', website: 'https://www.01zhuanche.com', category: 'AI办公', description: '首汽企业服务', isFree: false },
  { name: '嘀嗒出行企业AI', website: 'https://www.didapinche.com', category: 'AI办公', description: '嘀嗒企业服务', isFree: false },
  { name: '哈啰企业AI', website: 'https://www.hellobike.com', category: 'AI办公', description: '哈啰企业服务', isFree: false },
  { name: '美团单车企业AI', website: 'https://www.meituan.com/bike', category: 'AI办公', description: '美团单车企业', isFree: false },
  { name: '青桔单车企业AI', website: 'https://www.didiglobal.com/bike', category: 'AI办公', description: '青桔企业服务', isFree: false },
  { name: '小鹏汽车企业AI', website: 'https://www.xiaopeng.com', category: 'AI办公', description: '小鹏企业服务', isFree: false },
  { name: '蔚来汽车企业AI', website: 'https://www.nio.com', category: 'AI办公', description: '蔚来企业服务', isFree: false },
  { name: '理想汽车企业AI', website: 'https://www.lixiang.com', category: 'AI办公', description: '理想企业服务', isFree: false },
  { name: '比亚迪企业AI', website: 'https://www.byd.com', category: 'AI办公', description: '比亚迪企业服务', isFree: false },
  { name: '吉利汽车企业AI', website: 'https://www.geely.com', category: 'AI办公', description: '吉利企业服务', isFree: false },
  { name: '长城汽车企业AI', website: 'https://www.gwm.com.cn', category: 'AI办公', description: '长城企业服务', isFree: false },
  { name: '长安汽车企业AI', website: 'https://www.changan.com.cn', category: 'AI办公', description: '长安企业服务', isFree: false },
  { name: '上汽集团企业AI', website: 'https://www.saicmotor.com', category: 'AI办公', description: '上汽企业服务', isFree: false },
  { name: '广汽集团企业AI', website: 'https://www.gac.com.cn', category: 'AI办公', description: '广汽企业服务', isFree: false },
  { name: '东风汽车企业AI', website: 'https://www.dfmg.com.cn', category: 'AI办公', description: '东风企业服务', isFree: false },
  { name: '一汽集团企业AI', website: 'https://www.faw.com.cn', category: 'AI办公', description: '一汽企业服务', isFree: false },
  { name: '北汽集团企业AI', website: 'https://www.baicgroup.com.cn', category: 'AI办公', description: '北汽企业服务', isFree: false },
  { name: '奇瑞汽车企业AI', website: 'https://www.chery.cn', category: 'AI办公', description: '奇瑞企业服务', isFree: false },
];

// 随机打乱数组
export function shuffleArray<T>(array: T[]): T[] {
  const result = [...array];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}
